// ============================================================
// DB Schema Snapshot Generator
//
// Opens a fresh in-memory DB, runs all migrations, then dumps
// the canonical schema to server/src/db/__tests__/fixtures/schema.snapshot.sql
//
// Usage: npm run db:snapshot
// ============================================================

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Database from 'better-sqlite3';
import { runMigrations } from './migrate.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SNAPSHOT_PATH = path.join(__dirname, '__tests__/fixtures/schema.snapshot.sql');

const db = new Database(':memory:');
db.pragma('foreign_keys = ON');

runMigrations(db);

const rows = db.prepare(`
  SELECT type, name, sql
  FROM sqlite_master
  WHERE name NOT LIKE 'sqlite_%'
    AND name != '_migrations'
  ORDER BY type DESC, name ASC
`).all() as Array<{ type: string; name: string; sql: string }>;

const header = `-- Schema snapshot generated by: npm run db:snapshot\n-- Do not edit manually. Regenerate with: npm run db:snapshot\n-- Tables and indexes ordered by (type DESC, name ASC)\n\n`;
const body = rows.map(r => r.sql + ';').join('\n\n') + '\n';

fs.writeFileSync(SNAPSHOT_PATH, header + body, 'utf-8');
console.log(`Snapshot written to ${SNAPSHOT_PATH} (${rows.length} objects)`);
db.close();
