// helpers.ts — capability definitions, category configs, icon mapping
import {
  MessageSquare, Code, Zap, Brain, Globe, Mic, ImageIcon, Film,
  User, Bell, Cpu, Sparkles, Eye, TrendingUp,
  Shield, ArrowRight, CheckCircle2, ExternalLink, Star, Lock,
  Workflow, Play, Layers, Telescope, Activity,
  Camera, Link, Search
} from 'lucide-react';

// ── Types ────────────────────────────────────────────────────

export type Category = 'all' | 'chat' | 'create' | 'automate' | 'connect' | 'analyze';

export interface Capability {
  id: string;
  category: Exclude<Category, 'all'>;
  icon: typeof MessageSquare;
  color: string;
  glow: string;
  title: string;
  description: string;
  examples: string[];
  badge: 'Core' | 'Pro' | 'New';
  status?: 'limited' | 'degraded';
  navigateTo?: string;
  needsSetup?: boolean;
  wow?: string;
}

export interface CapabilitiesPageProps {
  onNavigate?: (page: string) => void;
  onOpenChat?: () => void;
}

// ── Capability definitions ────────────────────────────────────

export const capabilities: Capability[] = [
  // ── CHAT ──────────────────────────────────────────────────
  {
    id: 'multi-model-chat',
    category: 'chat',
    icon: Brain,
    color: 'var(--ag-violet)',
    glow: 'rgba(139,92,246,0.12)',
    title: 'Multi-Model Intelligence',
    description: 'Your agent automatically routes to the right AI brain — free Llama for quick answers, Kimi K2 for deep technical work — based on complexity and your credit balance.',
    examples: ['Explain CRDT data structures', 'Debug this TypeScript error', 'Design a URL shortener system'],
    badge: 'Core',
    wow: 'Routes across 5 AI models in real-time',
  },
  {
    id: 'voice-notes',
    category: 'chat',
    icon: Mic,
    color: 'var(--ag-violet)',
    glow: 'rgba(139,92,246,0.12)',
    title: 'Voice Notes',
    description: 'Send a voice message on Telegram and get a spoken audio reply back. Full Whisper transcription → agent reasoning → TTS pipeline.',
    examples: ["Voice: What's on my agenda?", 'Voice: Remind me at 5pm to ship the PR', 'Voice: Summarize what I built this week'],
    badge: 'Pro',
    needsSetup: true,
    wow: 'Complete speech-to-speech pipeline',
  },
  {
    id: 'web-crawler',
    category: 'chat',
    icon: Globe,
    color: 'var(--ag-cyan)',
    glow: 'rgba(139,92,246,0.12)',
    title: 'Live Web Research',
    description: 'Hand your agent any URL — job posting, article, competitor page — and get an instant structured summary with key insights extracted.',
    examples: ['Summarize this Hacker News thread: [URL]', 'What are the pricing tiers on this page?', 'Extract tech stack mentions from this blog'],
    badge: 'Core',
    wow: 'Reads any public web page on demand',
  },
  {
    id: 'memory-chat',
    category: 'chat',
    icon: Layers,
    color: 'var(--ag-cyan)',
    glow: 'rgba(139,92,246,0.12)',
    title: 'Context-Aware Conversations',
    description: 'Your agent remembers conversation history across sessions, extracting facts automatically — your stack, preferences, schedule — and weaving them into every reply.',
    examples: ['Remember I prefer TypeScript over Python', 'What did we discuss last week?', 'Keep in mind my deadline is March 15th'],
    badge: 'Core',
    wow: 'Persistent memory extracted from every chat',
  },
  {
    id: 'hinglish',
    category: 'chat',
    icon: Globe,
    color: 'var(--ag-cyan)',
    glow: 'rgba(139,92,246,0.12)',
    title: 'Hinglish & Indian Languages',
    description: 'Talk to your agent in Hinglish, Hindi, or Tanglish. It understands "kal subah 8 baje remind karo" as naturally as English. Built for Indian users first.',
    examples: ['kal subah 8 baje remind karo gym ke liye', 'swiggy pe 350 rupay kharcha hua', 'mujhe ek tweet likhne mein help karo'],
    badge: 'New',
    wow: 'Native Hinglish, Hindi, and Tanglish understanding',
  },
  {
    id: 'researcher',
    category: 'chat',
    icon: Telescope,
    color: 'var(--ag-cyan)',
    glow: 'rgba(139,92,246,0.12)',
    title: 'Agent-as-Researcher',
    description: 'Ask for deep research and your agent launches an async investigation — searching the web, synthesizing findings, and delivering a structured report via Telegram when done.',
    examples: ['Research best budget phones under 15000 in India', 'Compare React vs Vue for a solo dev', 'Find top 5 AI tools for content creators 2024'],
    badge: 'New',
    wow: 'Async research delivered to your Telegram',
  },

  // ── CREATE ────────────────────────────────────────────────
  {
    id: 'website-builder',
    category: 'create',
    icon: Code,
    color: '#BF5FFF',
    glow: 'rgba(191,95,255,0.12)',
    title: 'Live Website Builder',
    description: 'Describe any web page in plain English and get fully working, shareable HTML/CSS/JS with an instant preview link. Auto-saved to your Projects.',
    examples: ['Build a pricing page for a SaaS app', 'Create an interactive quiz about JavaScript', 'Make a portfolio hero with animated text effects'],
    badge: 'Core',
    navigateTo: 'website-builder',
    wow: 'Complete code + live preview link instantly',
  },
  {
    id: 'image-gen',
    category: 'create',
    icon: ImageIcon,
    color: '#BF5FFF',
    glow: 'rgba(191,95,255,0.12)',
    title: 'Image Generation',
    description: 'Turn text descriptions into studio-quality visuals — product mockups, social media graphics, concept art, logos. All saved to your media library.',
    examples: ['Generate a logo for a fintech startup', 'Illustrate a futuristic developer workspace', 'Create a Twitter banner for my portfolio'],
    badge: 'Pro',
    navigateTo: 'image-gen',
    wow: 'Studio-quality output from one sentence',
  },
  {
    id: 'video-gen',
    category: 'create',
    icon: Film,
    color: '#BF5FFF',
    glow: 'rgba(191,95,255,0.12)',
    title: 'Video Generation',
    description: 'Generate short video clips from text prompts. Perfect for social media content, product demos, and visual storytelling. Free providers currently unreachable — functionality is limited.',
    examples: ['Create a 10s product demo for my app', 'Generate a cinematic intro for my brand', 'Make an animated explainer for my SaaS'],
    badge: 'Pro',
    status: 'limited',
    navigateTo: 'video-gen',
    wow: 'Text-to-video in your media library',
  },
  {
    id: 'avatar-gen',
    category: 'create',
    icon: User,
    color: '#BF5FFF',
    glow: 'rgba(191,95,255,0.12)',
    title: 'AI Avatar Creator',
    description: 'Generate a professional or creative avatar from a text description and auto-set it as your profile picture instantly.',
    examples: ['Generate a professional headshot avatar', 'Make a cyberpunk-style avatar for my profile', 'Create a minimalist cartoon developer avatar'],
    badge: 'Pro',
    wow: 'Auto-updates your profile picture on creation',
  },
  {
    id: 'flashcards',
    category: 'create',
    icon: Layers,
    color: '#BF5FFF',
    glow: 'rgba(191,95,255,0.12)',
    title: 'Flashcards & Study',
    description: 'Create study flashcards from any topic. The agent generates question-answer pairs for spaced repetition learning.',
    examples: ['make flashcards for React hooks', 'create study cards for Python list comprehensions', 'quiz me on JavaScript closures'],
    badge: 'Core',
    wow: 'Auto-generated Q&A pairs from any topic',
  },
  {
    id: 'code-tools',
    category: 'create',
    icon: Code,
    color: '#BF5FFF',
    glow: 'rgba(191,95,255,0.12)',
    title: 'Code Review & PR',
    description: 'Paste code for an instant review, or describe your changes for a professional PR description. Built for developers shipping fast.',
    examples: ['review this code: function add(a,b) { return a+b }', 'write a PR description for: added dark mode', 'audit SEO of my portfolio page'],
    badge: 'Core',
    wow: 'Instant code review + PR descriptions',
  },

  // ── AUTOMATE ──────────────────────────────────────────────
  {
    id: 'smart-reminders',
    category: 'automate',
    icon: Bell,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Natural Language Reminders',
    description: 'Set reminders in plain English from any channel — chat, Telegram, or WhatsApp. The agent parses time, channel, and category automatically.',
    examples: ['Remind me in 2 hours to ship the PR', 'Set a reminder every Monday at 9am for standup', 'Alert me 30 minutes before my dentist appointment'],
    badge: 'Core',
    navigateTo: 'reminders',
    wow: 'Works on Telegram, WhatsApp, and push',
  },
  {
    id: 'expense-tracker',
    category: 'automate',
    icon: TrendingUp,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Expense Tracker',
    description: 'Track spending in natural language — English or Hinglish. Auto-categorizes merchants (Swiggy→food, Uber→transport) and shows monthly summaries. Zero-latency regex fast-path.',
    examples: ['spent 450 on uber to airport', 'swiggy pe 350 rupay kharch kiye', 'show my expenses this month'],
    badge: 'New',
    wow: 'Auto-categorizes Indian merchants, 660ms response',
  },
  {
    id: 'habit-tracker',
    category: 'automate',
    icon: CheckCircle2,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Habit Tracker & Coach',
    description: 'Track daily habits with streaks, get compassionate nudge notifications when you miss a day, and view weekly progress. Includes Reschedule/Skip buttons on Telegram.',
    examples: ['gym kiya aaj', 'track my meditation habit daily', 'show my habits — how is my streak?'],
    badge: 'New',
    wow: 'Compassionate AI coach with Telegram inline buttons',
  },
  {
    id: 'focus-sessions',
    category: 'automate',
    icon: Play,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Focus Sessions',
    description: 'Start a Pomodoro timer with one message. The agent parses your goal and duration, starts the session instantly, and notifies you when it ends.',
    examples: ['start a 25 minute focus session to write my blog', 'pomodoro — working on Figma designs', 'focus mode for deep work'],
    badge: 'Core',
    wow: 'Instant start with zero-latency regex parser',
  },
  {
    id: 'proactive-engine',
    category: 'automate',
    icon: Sparkles,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Proactive Engine',
    description: 'Your agent reaches out first — morning briefings, reminder previews 30 minutes ahead, habit nudges at 11am, and weekly expense digests. You never have to ask.',
    examples: ['morning briefing sent automatically at 7am', 'reminder preview 30 min before due', 'habit nudge: "You haven\'t logged yoga today"'],
    badge: 'New',
    wow: 'Agent reaches out first — no prompting needed',
  },
  {
    id: 'daily-operator',
    category: 'automate',
    icon: Mic,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Daily Operator Mode',
    description: 'Get your morning briefing as a voice note on Telegram. Synthesized via edge-tts, delivered as an audio message you can listen to on your commute.',
    examples: ['morning voice briefing on Telegram', 'daily summary as audio message', 'briefing with tasks + habits + weather'],
    badge: 'New',
    wow: 'Voice briefing delivered to Telegram every morning',
  },
  {
    id: 'automations',
    category: 'automate',
    icon: Zap,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Automation Workflows',
    description: 'Create trigger-based automations: schedule tasks with cron, call APIs when your server goes down, fire webhooks on any event.',
    examples: ['Back up my database daily at 3am', 'Notify me on Telegram when server health drops', 'Call my API every hour and log the response'],
    badge: 'Core',
    navigateTo: 'automations',
    wow: 'Cron, webhook, and health-down triggers',
  },
  {
    id: 'fleet-agents',
    category: 'automate',
    icon: Cpu,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Weebo Fleet',
    description: 'Deploy up to 3 background agents that run tasks in parallel — hit APIs, send messages, manage reminders, deploy your portfolio — while you sleep.',
    examples: ['Monitor 3 endpoints simultaneously', 'Run a portfolio deploy in the background', 'Queue API calls without blocking the chat'],
    badge: 'Pro',
    navigateTo: 'pico',
    wow: '3 parallel slots, round-robin scheduling',
  },
  {
    id: 'email',
    category: 'automate',
    icon: MessageSquare,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Agent-Sent Emails',
    description: 'Ask your agent to email you anything — a plan, code snippet, weekly summary, or formatted document. Delivered instantly to your inbox.',
    examples: ["Email me today's task summary", 'Send the code we just generated to my inbox', 'Email me a formatted version of this plan'],
    badge: 'Core',
    wow: 'Delivered to your configured email address',
  },
  {
    id: 'workflows',
    category: 'automate',
    icon: Workflow,
    color: '#00FF88',
    glow: 'rgba(0,255,136,0.12)',
    title: 'Windmill Workflows',
    description: 'Trigger Windmill automation flows directly from chat. Bridge your AI agent to any existing workflow, script, or external system.',
    examples: ['Run my CI pipeline flow', 'Trigger the customer onboarding workflow', 'Fire the nightly data sync automation'],
    badge: 'Pro',
    wow: 'Connects your agent to any automation platform',
  },

  // ── CONNECT ───────────────────────────────────────────────
  {
    id: 'telegram',
    category: 'connect',
    icon: MessageSquare,
    color: '#F59E0B',
    glow: 'rgba(245,158,11,0.12)',
    title: 'Telegram Integration',
    description: 'Full two-way agent chat in Telegram. Commands, reminders, voice notes, code generation — your entire agent lives in your phone\'s chat.',
    examples: ['/remind check email at 5pm', 'Build a landing page for my SaaS', '/credits — check your balance'],
    badge: 'Core',
    needsSetup: true,
    wow: 'Your agent lives in your Telegram',
  },
  {
    id: 'portfolio-chat',
    category: 'connect',
    icon: Eye,
    color: '#F59E0B',
    glow: 'rgba(245,158,11,0.12)',
    title: 'Portfolio Visitor AI',
    description: 'Visitors to your public portfolio chat with an AI version of you — trained on your bio, skills, and projects. Knows your availability and escalates questions to you.',
    examples: ['Is she available for a project in March?', 'What technologies does he work with?', 'Can I schedule a 30-minute call this week?'],
    badge: 'Core',
    navigateTo: 'portfolio',
    wow: 'Your AI twin represents you 24/7 to recruiters',
  },
  {
    id: 'visitor-escalation',
    category: 'connect',
    icon: ArrowRight,
    color: '#F59E0B',
    glow: 'rgba(245,158,11,0.12)',
    title: 'Smart Visitor Escalation',
    description: 'When a portfolio visitor asks something beyond your AI\'s knowledge, it pings you via Telegram with the question. You reply — it relays your answer instantly.',
    examples: ['Visitor asks: "Is she open for consulting?"', 'You swipe-reply on Telegram: "Yes, Wednesday"', 'Agent delivers your answer to the visitor'],
    badge: 'New',
    wow: 'Native Telegram reply matching — zero false positives',
  },
  {
    id: 'social-media',
    category: 'connect',
    icon: Globe,
    color: '#F59E0B',
    glow: 'rgba(245,158,11,0.12)',
    title: 'Social Media Publisher',
    description: 'Draft, schedule, and publish posts across social platforms from chat. Let the agent handle content while you focus on building.',
    examples: ['Post about my new project on LinkedIn', 'Schedule 5 tweets about what I\'m building', 'Draft a thread about my latest release'],
    badge: 'Pro',
    navigateTo: 'social-media',
    wow: 'Draft, schedule, and publish from one prompt',
  },
  {
    id: 'multi-agent',
    category: 'connect',
    icon: Cpu,
    color: '#F59E0B',
    glow: 'rgba(245,158,11,0.12)',
    title: 'Multi-Agent Launch Mode',
    description: 'Say "launch mode" and 3 specialized agents (Forge, Aria, Pulse) tackle your question simultaneously from different angles — technical, creative, and trending.',
    examples: ['launch mode: plan my app launch strategy', 'all agents: best tech stack for 2024?', 'multi-agent: analyze my career switch'],
    badge: 'New',
    wow: '3 agents working in parallel on one question',
  },

  // ── ANALYZE ───────────────────────────────────────────────
  {
    id: 'memory',
    category: 'analyze',
    icon: Brain,
    color: '#EC4899',
    glow: 'rgba(236,72,153,0.12)',
    title: 'Persistent Memory',
    description: 'Your agent automatically extracts and stores facts from every conversation — your stack, preferences, goals, and schedule — then uses them in future sessions.',
    examples: ['Remember I always use pnpm not npm', 'Note my current project is a fintech SaaS', 'Save that I work best in the mornings'],
    badge: 'Core',
    navigateTo: 'memory',
    wow: 'Auto-extracts facts without you asking',
  },
  {
    id: 'usage-analytics',
    category: 'analyze',
    icon: TrendingUp,
    color: '#EC4899',
    glow: 'rgba(236,72,153,0.12)',
    title: 'Usage Intelligence',
    description: 'See exactly where your AI credits go — per model, per feature, per hour of day. Forecast monthly spend and optimize your usage patterns.',
    examples: ['Show my top 5 credit-consuming actions', 'What time of day do I use AI the most?', 'Compare this month vs last month spend'],
    badge: 'Core',
    navigateTo: 'usage',
    wow: 'Per-model cost breakdown + spend forecasting',
  },
  {
    id: 'health',
    category: 'analyze',
    icon: Activity,
    color: '#EC4899',
    glow: 'rgba(236,72,153,0.12)',
    title: 'System Health Monitor',
    description: 'Real-time health checks on all connected services. Automatic Telegram alerts when anything goes down — before your users notice.',
    examples: ['Show me uptime over the last 30 days', 'Alert me if API response exceeds 5 seconds', 'Check health of my Telegram integration'],
    badge: 'Core',
    navigateTo: 'health',
    wow: 'Triggers automations on health events',
  },
  {
    id: 'global-search',
    category: 'analyze',
    icon: Search,
    color: '#EC4899',
    glow: 'rgba(236,72,153,0.12)',
    title: 'Ctrl+K Global Search',
    description: 'Press Cmd/Ctrl+K anywhere in the dashboard to instantly search across notes, reminders, habits, and memories. Finds what you need in milliseconds.',
    examples: ['Ctrl+K → search "meeting notes"', 'Quick find across all your data', 'Search habits, notes, reminders at once'],
    badge: 'Core',
    wow: 'Instant cross-entity search from anywhere',
  },
  {
    id: 'telescope',
    category: 'analyze',
    icon: Telescope,
    color: '#EC4899',
    glow: 'rgba(236,72,153,0.12)',
    title: 'Explore Directory',
    description: 'Discover other builders, creatives, and professionals in the Agentin ecosystem. Visit their portfolios, chat with their AI agents.',
    examples: ['Find TypeScript engineers in my area', 'Browse portfolios tagged "AI builder"', 'Discover open-to-work developers'],
    badge: 'Core',
    wow: 'Browse a community of AI-powered professionals',
  },
];

// ── Pipeline steps ─────────────────────────────────────────

export const pipelineSteps = [
  { label: 'Your message', detail: '"build me a hello world page"', color: 'var(--ag-cyan)', icon: MessageSquare },
  { label: 'Intent classified', detail: 'coding → complex', color: '#BF5FFF', icon: Brain },
  { label: 'Model selected', detail: 'Kimi K2 (best for coding)', color: '#F59E0B', icon: Zap },
  { label: 'Action extracted', detail: 'generate_code { title, html, css, js }', color: '#00FF88', icon: Code },
  { label: 'Artifact saved', detail: 'auto-added to My Projects', color: '#EC4899', icon: CheckCircle2 },
  { label: 'Preview delivered', detail: 'api.../preview/userId/abc', color: 'var(--ag-cyan)', icon: ExternalLink },
];

// ── Hidden powers ──────────────────────────────────────────

export const hiddenPowers = [
  { icon: Mic, color: 'var(--ag-cyan)', title: 'Full voice loop on Telegram', description: 'Speak to your agent, get audio back. No typing ever needed — complete speech-to-speech pipeline on your phone.' },
  { icon: Eye, color: '#BF5FFF', title: 'You have a 24/7 AI twin', description: 'Your portfolio agent knows your projects, skills, and availability. Recruiters get accurate, helpful answers at 3am while you sleep.' },
  { icon: ArrowRight, color: '#F59E0B', title: 'Swipe-to-reply escalation', description: 'Swipe-reply on a visitor escalation notification in Telegram and your agent knows exactly which question you\'re answering. Zero ambiguity.' },
  { icon: Lock, color: '#00FF88', title: 'Visitor contact capture', description: 'Your portfolio AI naturally collects visitor names and contact info during the conversation, building your professional network automatically.' },
  { icon: Cpu, color: '#EC4899', title: '3 agents running in parallel', description: 'Queue tasks across 3 background slots simultaneously — they work while you\'re offline, reporting back via Telegram when done.' },
  { icon: Code, color: '#BF5FFF', title: 'Code is yours forever', description: 'Every website, snippet, and artifact your agent generates is saved with a permanent preview link. It also appears in your portfolio Projects.' },
  { icon: Shield, color: 'var(--ag-cyan)', title: 'Multi-tier keyword routing', description: 'The escalation system uses 3-tier matching: native Telegram reply, keyword scoring, and smart fall-through — so chat requests never get eaten.' },
  { icon: Star, color: '#F59E0B', title: 'Credits forecast your month', description: 'The sidebar shows your current spend and forecasts your full monthly bill — so you never get surprised at the end of the cycle.' },
  { icon: Camera, color: '#00FF88', title: 'Receipt OCR → auto expense', description: 'Send a photo of any receipt on Telegram — Groq vision reads it, extracts amount and merchant, and auto-logs the expense. No typing needed.' },
  { icon: Eye, color: 'var(--ag-cyan)', title: 'Screenshot fast-path', description: 'Say "take screenshot of [URL]" and your agent captures a full-page screenshot via crawl4ai and sends it as a Telegram photo in seconds.' },
  { icon: Link, color: '#BF5FFF', title: 'Links extraction', description: 'Say "get links from [URL]" and your agent crawls the page, extracts every link, and sends you a clean formatted list — perfect for research.' },
  { icon: Brain, color: '#EC4899', title: 'Context threading via FTS5', description: 'Your agent runs full-text search over your entire conversation history — it can recall what you discussed weeks ago and weave it into the current reply.' },
];

// ── Category config ────────────────────────────────────────

export const categoryConfig: Record<Category, { label: string; color: string; emoji: string }> = {
  all: { label: 'All Powers', color: 'var(--ag-text-primary)', emoji: '⚡' },
  chat: { label: 'Chat & Answer', color: 'var(--ag-cyan)', emoji: '🧠' },
  create: { label: 'Create & Build', color: '#BF5FFF', emoji: '⚗️' },
  automate: { label: 'Automate', color: '#00FF88', emoji: '🔄' },
  connect: { label: 'Connect', color: '#F59E0B', emoji: '🌐' },
  analyze: { label: 'Analyze', color: '#EC4899', emoji: '📊' },
};
