// Compatibility wrapper — re-exports from activity-stream.
// All new code should import from '../../../services/activity-stream.js' directly.

export {
	type AgentStateEvent,
	type AgentStateType,
	addStateClient,
	broadcastAgentState,
	emitCommReceived,
	emitCommSent,
	emitDelegation,
	emitDone,
	emitIdle,
	emitResponding,
	emitTaskCompleted,
	emitError,
	emitGoalCompleted,
	emitGoalStarted,
	emitStreakMilestone,
	emitTaskFailed,
	emitTaskStarted,
	emitThinking,
	emitToolCall,
	emitToolResult,
	getAgentLastState,
	getAllAgentStates,
	getConnectedClientCount,
	getRecentEvents,
	initRedisPubSub,
	isRedisPubSubEnabled,
	publishToRedis,
	removeStateClient,
} from "../../../services/activity-stream.js";
