// ============================================================
// Agent-Initiated Notifications — Push System
//
// Agents proactively push notifications to users via:
// - SSE (real-time in-app)
// - Telegram (if connected)
// - Notification store (in-app bell icon)
//
// Notifications are generated by:
// - Goal progress milestones
// - Step completions
// - Delegation results
// - Proactive insights
// - Anomaly detection (expense spikes, missed habits)
// ============================================================

import { v4 as uuid } from 'uuid';
import { db } from '../../../db/index.js';
import { logger } from '../../../logger.js';
import { broadcastAgentState } from './agent-state-bus.js';
import { getPersonality } from '../../../prompts/personalities.js';
import type { AnyAgentId } from '../types/goals.js';

// ── Types ───────────────────────────────────────────────────

export type NotificationType =
  | 'goal_progress' | 'goal_completed' | 'step_completed' | 'step_failed'
  | 'delegation_complete' | 'agent_insight' | 'anomaly' | 'checkin'
  | 'suggestion' | 'celebration';

export interface AgentNotification {
  id: string;
  user_id: string;
  agent_id: string;
  type: NotificationType;
  title: string;
  message: string;
  action_url: string | null;
  metadata: string;
  read: number;
  created_at: string;
}

// ── DB Table (created in db/index.ts migration block) ───────

export function ensureNotificationTable(): void {
  try {
    db.exec(`
      CREATE TABLE IF NOT EXISTS agent_notifications (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        agent_id TEXT NOT NULL,
        type TEXT NOT NULL,
        title TEXT NOT NULL,
        message TEXT NOT NULL DEFAULT '',
        action_url TEXT,
        metadata TEXT DEFAULT '{}',
        read INTEGER DEFAULT 0,
        created_at TEXT DEFAULT (datetime('now'))
      );
      CREATE INDEX IF NOT EXISTS idx_agent_notifications_user ON agent_notifications(user_id, read, created_at DESC);
    `);
  } catch { /* already exists */ }
}

// Call on module init
ensureNotificationTable();

// ── Send Notification ───────────────────────────────────────

export async function sendAgentNotification(
  userId: string,
  agentId: AnyAgentId,
  type: NotificationType,
  title: string,
  message: string,
  options?: { actionUrl?: string; metadata?: Record<string, unknown>; sendTelegram?: boolean },
): Promise<AgentNotification> {
  const id = uuid();
  const personality = getPersonality(agentId);

  // Store in DB
  db.prepare(`
    INSERT INTO agent_notifications (id, user_id, agent_id, type, title, message, action_url, metadata)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `).run(id, userId, agentId, type, title, message, options?.actionUrl || null, JSON.stringify(options?.metadata || {}));

  // Broadcast via SSE (real-time in-app)
  broadcastAgentState(userId, {
    agentId,
    agentName: personality.name,
    state: 'responding',
    content: `${personality.emoji} ${title}: ${message}`,
  });

  // Send via Telegram if requested — honor user notification preferences
  if (options?.sendTelegram !== false) {
    try {
      // Check if user has agent notifications enabled
      const config = db.prepare('SELECT notif_agents, quiet_start, quiet_end FROM agent_configs WHERE user_id = ?')
        .get(userId) as { notif_agents: number | null; quiet_start: string | null; quiet_end: string | null } | undefined;
      const agentNotifsEnabled = config?.notif_agents !== 0; // default true if null

      // Check quiet hours (using user's timezone)
      let inQuietHours = false;
      if (config?.quiet_start && config?.quiet_end) {
        const userRow = db.prepare('SELECT timezone FROM users WHERE id = ?').get(userId) as { timezone: string | null } | undefined;
        const tz = userRow?.timezone || 'UTC';
        let nowH: number, nowM: number;
        try {
          const nowStr = new Date().toLocaleString('en-US', { timeZone: tz, hour: 'numeric', minute: 'numeric', hour12: false });
          const parts = nowStr.split(':');
          nowH = parseInt(parts[0], 10);
          nowM = parseInt(parts[1], 10);
        } catch {
          nowH = new Date().getUTCHours();
          nowM = new Date().getUTCMinutes();
        }
        const nowMin = nowH * 60 + nowM;
        const [sH, sM] = config.quiet_start.split(':').map(Number);
        const [eH, eM] = config.quiet_end.split(':').map(Number);
        const startMin = sH * 60 + sM;
        const endMin = eH * 60 + eM;
        inQuietHours = startMin <= endMin
          ? (nowMin >= startMin && nowMin < endMin)
          : (nowMin >= startMin || nowMin < endMin);
      }

      if (agentNotifsEnabled && !inQuietHours) {
        const link = db.prepare(
          "SELECT external_id FROM channel_links WHERE user_id = ? AND channel = 'telegram' AND is_verified = 1 LIMIT 1"
        ).get(userId) as { external_id: string } | undefined;

        if (link) {
          const { sendTelegramMessage } = await import('../../../services/telegram.js');
          const telegramMsg = `${personality.emoji} *${personality.name}*\n${title}\n\n${message}`;
          await sendTelegramMessage(link.external_id, telegramMsg);
        }
      }
    } catch {
      // Telegram send is non-critical
    }
  }

  logger.info({ userId, agentId, type, title }, 'agent-notification:sent');
  return db.prepare('SELECT * FROM agent_notifications WHERE id = ?').get(id) as AgentNotification;
}

// ── Read/Manage Notifications ───────────────────────────────

export function getNotifications(userId: string, unreadOnly = false, limit = 50): AgentNotification[] {
  const query = unreadOnly
    ? 'SELECT * FROM agent_notifications WHERE user_id = ? AND read = 0 ORDER BY created_at DESC LIMIT ?'
    : 'SELECT * FROM agent_notifications WHERE user_id = ? ORDER BY created_at DESC LIMIT ?';
  return db.prepare(query).all(userId, limit) as AgentNotification[];
}

export function getUnreadCount(userId: string): number {
  return (db.prepare('SELECT COUNT(*) as c FROM agent_notifications WHERE user_id = ? AND read = 0').get(userId) as { c: number }).c;
}

export function markAsRead(notificationId: string, userId: string): boolean {
  return db.prepare('UPDATE agent_notifications SET read = 1 WHERE id = ? AND user_id = ?').run(notificationId, userId).changes > 0;
}

export function markAllAsRead(userId: string): number {
  return db.prepare('UPDATE agent_notifications SET read = 1 WHERE user_id = ? AND read = 0').run(userId).changes;
}

export function deleteNotification(notificationId: string, userId: string): boolean {
  return db.prepare('DELETE FROM agent_notifications WHERE id = ? AND user_id = ?').run(notificationId, userId).changes > 0;
}

// ── Convenience Notification Builders ───────────────────────

export async function notifyGoalProgress(userId: string, agentId: AnyAgentId, goalTitle: string, progress: number, goalId: string): Promise<void> {
  const milestones = [25, 50, 75, 100];
  if (!milestones.includes(progress)) return;

  const title = progress === 100 ? `Goal completed!` : `Goal ${progress}% complete`;
  const message = progress === 100
    ? `"${goalTitle}" is done! Great work.`
    : `"${goalTitle}" is now ${progress}% complete. Keep going!`;

  await sendAgentNotification(userId, agentId, progress === 100 ? 'goal_completed' : 'goal_progress',
    title, message, { actionUrl: `/goals/${goalId}` });
}

export async function notifyStepCompleted(userId: string, agentId: AnyAgentId, stepTitle: string, goalTitle: string): Promise<void> {
  await sendAgentNotification(userId, agentId, 'step_completed',
    'Step completed', `"${stepTitle}" for goal "${goalTitle}" is done.`, { sendTelegram: false });
}

export async function notifyDelegationResult(userId: string, fromAgent: AnyAgentId, toAgent: AnyAgentId, task: string, success: boolean): Promise<void> {
  const toName = getPersonality(toAgent).name;
  const title = success ? `${toName} completed task` : `${toName} needs help`;
  const message = success
    ? `${toName} finished: "${task.slice(0, 100)}"`
    : `${toName} couldn't complete: "${task.slice(0, 100)}"`;

  await sendAgentNotification(userId, fromAgent, 'delegation_complete', title, message);
}

export async function notifyAgentInsight(userId: string, agentId: AnyAgentId, insight: string): Promise<void> {
  await sendAgentNotification(userId, agentId, 'agent_insight', 'Agent Insight', insight);
}
