import { useState } from 'react';
import { Award, Plus, Trash2 } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { SectionCard } from '@/components/agentin';
import type { PortfolioMilestone } from '@/types';

const emptyMilestone: PortfolioMilestone = { date: '', title: '', description: '', autoGenerated: false };

interface MilestonesTabProps {
  milestones: PortfolioMilestone[];
  setMilestones: (v: PortfolioMilestone[]) => void;
}

export function MilestonesTab({ milestones, setMilestones }: MilestonesTabProps) {
  const [editingMilestone, setEditingMilestone] = useState<PortfolioMilestone | null>(null);
  const [editingMilestoneIdx, setEditingMilestoneIdx] = useState<number | null>(null);

  const saveMilestone = () => {
    if (!editingMilestone || !editingMilestone.title.trim()) return;
    if (editingMilestoneIdx !== null) {
      const updated = [...milestones];
      updated[editingMilestoneIdx] = editingMilestone;
      setMilestones(updated);
    } else {
      setMilestones([...milestones, editingMilestone]);
    }
    setEditingMilestone(null);
    setEditingMilestoneIdx(null);
  };

  const deleteMilestone = (idx: number) => {
    setMilestones(milestones.filter((_, i) => i !== idx));
  };

  return (
    <SectionCard title="Milestones" subtitle="Key achievements and career highlights">
      <div className="flex items-center justify-end mb-4">
        <Button
          onClick={() => { setEditingMilestone({ ...emptyMilestone }); setEditingMilestoneIdx(null); }}
          className="bg-[#8B5CF6] hover:bg-[#7C3AED] min-h-[44px]"
        >
          <Plus className="w-4 h-4 mr-2" />Add Milestone
        </Button>
      </div>
      <div className="space-y-4">
        {/* Inline form */}
        {editingMilestone && (
          <div className="p-4 rounded-lg bg-[var(--ag-bg-base)] shadow-[0_0_0_1px_rgba(139,92,246,0.15),0_2px_8px_rgba(0,0,0,0.12)] space-y-3">
            <div className="grid md:grid-cols-2 gap-3">
              <div>
                <label className="text-sm text-[var(--ag-text-muted)] mb-1 block">Title *</label>
                <Input
                  value={editingMilestone.title}
                  onChange={(e) => setEditingMilestone({ ...editingMilestone, title: e.target.value })}
                  placeholder="e.g. Launched SaaS product"
                  className="bg-[var(--ag-bg-surface)] border-[rgba(139,92,246,0.15)] text-[var(--ag-text-primary)]"
                />
              </div>
              <div>
                <label className="text-sm text-[var(--ag-text-muted)] mb-1 block">Date</label>
                <Input
                  value={editingMilestone.date}
                  onChange={(e) => setEditingMilestone({ ...editingMilestone, date: e.target.value })}
                  placeholder="2025-01 or Jan 2025"
                  className="bg-[var(--ag-bg-surface)] border-[rgba(139,92,246,0.15)] text-[var(--ag-text-primary)]"
                />
              </div>
            </div>
            <div>
              <label className="text-sm text-[var(--ag-text-muted)] mb-1 block">Description</label>
              <textarea
                value={editingMilestone.description}
                onChange={(e) => setEditingMilestone({ ...editingMilestone, description: e.target.value })}
                placeholder="What happened and why it matters"
                className="w-full p-3 rounded-xl bg-[var(--ag-bg-surface)] border border-[rgba(139,92,246,0.15)] text-[var(--ag-text-primary)] min-h-[80px] resize-none focus:outline-none focus:border-[var(--ag-violet)]"
              />
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={() => { setEditingMilestone(null); setEditingMilestoneIdx(null); }}
                className="border-[rgba(139,92,246,0.15)]"
              >
                Cancel
              </Button>
              <Button onClick={saveMilestone} disabled={!editingMilestone.title.trim()} className="bg-[#8B5CF6] hover:bg-[#7C3AED] min-h-[44px]">
                {editingMilestoneIdx !== null ? 'Update' : 'Add'}
              </Button>
            </div>
          </div>
        )}

        {milestones.length === 0 && !editingMilestone && (
          <div className="text-center py-8">
            <Award className="w-10 h-10 text-[#EC4899]/30 mx-auto mb-3" />
            <p className="text-[var(--ag-text-muted)]">No milestones yet</p>
          </div>
        )}

        {/* Timeline list */}
        <div className="space-y-0">
          {milestones.map((milestone, idx) => (
            <div key={idx} className="flex gap-3 md:gap-4 group">
              <div className="flex flex-col items-center shrink-0">
                <div className="w-3 h-3 rounded-full bg-[#EC4899] mt-1.5" />
                {idx < milestones.length - 1 && <div className="w-0.5 flex-1 bg-[#EC4899]/20" />}
              </div>
              <div className="flex-1 pb-6 min-w-0">
                <div className="flex flex-col md:flex-row md:items-start justify-between gap-1">
                  <div className="min-w-0">
                    <div className="text-xs text-[#EC4899] font-mono mb-1">{milestone.date}</div>
                    <div className="font-medium text-[var(--ag-text-primary)]">{milestone.title}</div>
                    {milestone.description && <div className="text-sm text-[var(--ag-text-muted)] mt-1">{milestone.description}</div>}
                  </div>
                  <div className="flex gap-1 md:opacity-0 md:group-hover:opacity-100 transition-opacity shrink-0 mt-2 md:mt-0">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => { setEditingMilestone({ ...milestone }); setEditingMilestoneIdx(idx); }}
                      className="text-[#EC4899] hover:text-[#EC4899] min-h-[44px] min-w-[44px] press-scale focus-visible:ring-2 focus-visible:ring-[#8B5CF6]/50"
                      aria-label="Edit milestone"
                    >
                      Edit
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => deleteMilestone(idx)}
                      className="text-[#FF6161] hover:text-[#FF6161] min-h-[44px] min-w-[44px] press-scale focus-visible:ring-2 focus-visible:ring-[#8B5CF6]/50"
                      aria-label="Delete milestone"
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </SectionCard>
  );
}
