// ============================================================
// Artifact Routes — Public Preview & Management for Generated Code
//
// Provides live website preview for HTML/CSS/JS artifacts created
// via the generate_code action. Artifacts are served at:
//   /preview/:userId/:artifactId  — full-page preview
//   /api/artifacts/:id            — JSON API (requires auth)
// ============================================================

import { Router } from 'express';
import { db } from '../db/index.js';
import { logger } from '../logger.js';
import { requireAuth, type AuthRequest } from '../middleware/auth.js';
import { v4 as uuid } from 'uuid';

export const artifactsRouter = Router();

// ---- Public Preview Route (no auth required) ----
// Serves the artifact as a full HTML page with inline CSS/JS
artifactsRouter.get('/:userId/:artifactId', (req, res) => {
  const { userId, artifactId } = req.params;

  try {
    const artifact = db.prepare(
      'SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?'
    ).get(artifactId, userId) as {
      id: string;
      user_id: string;
      title: string;
      html: string;
      css: string;
      js: string;
      created_at: string;
    } | undefined;

    if (!artifact) {
      res.status(404).send(`
        <!DOCTYPE html>
        <html>
        <head><title>Preview Not Found</title></head>
        <body style="font-family: system-ui; display: flex; align-items: center; justify-content: center; height: 100vh; margin: 0; background: #0a0a0a; color: #fff;">
          <div style="text-align: center;">
            <h1>🔍 Preview Not Found</h1>
            <p>This project doesn't exist or has been removed.</p>
          </div>
        </body>
        </html>
      `);
      return;
    }

    // CSP override for preview pages: allow inline scripts/styles since these are
    // sandboxed user-generated artifacts that intentionally contain inline JS/CSS.
    const previewCsp = [
      "default-src 'self' data: blob:",
      "script-src 'unsafe-inline' 'unsafe-eval' https: http:",
      "style-src 'unsafe-inline' 'self' https: http:",
      "img-src * data: blob:",
      "font-src * data: blob:",
      "connect-src *",
      "media-src *",
      "frame-ancestors 'none'",
      "object-src 'none'",
    ].join('; ');

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('X-Frame-Options', 'SAMEORIGIN');
    res.setHeader('Content-Security-Policy', previewCsp);

    // If the artifact is a complete HTML document (generated by LLM — contains its own
    // <head>/<body>/<script> structure), serve it directly to avoid invalid nested HTML.
    const isCompleteDoc = /^\s*<!DOCTYPE\s/i.test(artifact.html || '') ||
                          /^\s*<html[\s>]/i.test(artifact.html || '');
    if (isCompleteDoc && !artifact.css && !artifact.js) {
      res.send(artifact.html);
    } else {
      // Template-based artifact: separate html/css/js — compose them into a wrapper page.
      const previewHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(artifact.title)} — Agentin Preview</title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; padding: 0; }
    ${artifact.css || ''}
  </style>
</head>
<body>
  ${artifact.html || ''}
  <script>
    console.log('🔧 Agentin Preview — Project: ${escapeJs(artifact.title)}');
    try {
      ${artifact.js || ''}
    } catch (err) {
      console.error('Script error:', err);
    }
  </script>
</body>
</html>`;
      res.send(previewHtml);
    }

    // Log view (non-blocking)
    try {
      db.prepare(`INSERT INTO activity_log (id, user_id, action, details, icon) VALUES (?, ?, 'Artifact preview viewed', ?, 'eye')`)
        .run(uuid(), userId, `Artifact: ${artifact.title}`);
    } catch { /* non-fatal */ }

  } catch (err) {
    logger.error({ err, userId, artifactId }, 'Artifact preview error');
    res.status(500).send('Preview unavailable');
  }
});

// ---- List User's Artifacts (auth required) ----
artifactsRouter.get('/', requireAuth, (req: AuthRequest, res) => {
  const artifacts = db.prepare(
    'SELECT id, title, type, created_at, expires_at FROM generated_artifacts WHERE user_id = ? ORDER BY created_at DESC'
  ).all(req.userId!) as Array<{
    id: string;
    title: string;
    type: string;
    created_at: string;
    expires_at: string | null;
  }>;

  const baseUrl = `${req.protocol}://${req.get('host')}`;
  res.json({
    artifacts: artifacts.map(a => ({
      id: a.id,
      title: a.title,
      type: a.type,
      createdAt: a.created_at,
      expiresAt: a.expires_at,
      previewUrl: `${baseUrl}/preview/${req.userId}/${a.id}`,
    })),
  });
});

import { saveArtifactPermanently } from '../services/artifact-cleanup.js';

// ---- Get Single Artifact (auth required) ----
artifactsRouter.get('/:id', requireAuth, (req: AuthRequest, res) => {
  const artifact = db.prepare(
    'SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?'
  ).get(req.params.id, req.userId!) as Record<string, unknown> | undefined;

  if (!artifact) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  const baseUrl = `${req.protocol}://${req.get('host')}`;
  res.json({
    ...artifact,
    previewUrl: `${baseUrl}/preview/${req.userId}/${artifact.id}`,
  });
});

// ---- Create Artifact (auth required) ----
// Allows the Dev Mode builder to create a new artifact directly without going through the AI agent.
artifactsRouter.post('/', requireAuth, (req: AuthRequest, res) => {
  const { title, html, css, js } = req.body as Record<string, string>;

  if (!title || title.trim().length === 0) {
    res.status(400).json({ error: 'title is required' });
    return;
  }

  const id = uuid();
  const expiresAt = new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString();

  db.prepare(
    `INSERT INTO generated_artifacts (id, user_id, type, title, html, css, js, expires_at)
     VALUES (?, ?, 'code', ?, ?, ?, ?, ?)`
  ).run(id, req.userId!, title.trim(), html || '', css || '', js || '', expiresAt);

  const baseUrl = `${req.protocol}://${req.get('host')}`;
  res.status(201).json({
    id,
    title: title.trim(),
    type: 'code',
    html: html || '',
    css: css || '',
    js: js || '',
    previewUrl: `${baseUrl}/preview/${req.userId}/${id}`,
    createdAt: new Date().toISOString(),
    expiresAt,
  });
});

// ---- Save Artifact Permanently (remove expiration) ----
artifactsRouter.post('/:id/save', requireAuth, (req: AuthRequest, res) => {
  const success = saveArtifactPermanently(req.params.id, req.userId!);
  if (!success) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }
  res.json({ success: true, message: 'Artifact saved permanently' });
});

// ---- Delete Artifact (auth required) ----
artifactsRouter.delete('/:id', requireAuth, (req: AuthRequest, res) => {
  const result = db.prepare(
    'DELETE FROM generated_artifacts WHERE id = ? AND user_id = ?'
  ).run(req.params.id, req.userId!);

  if (result.changes === 0) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  res.json({ success: true, message: 'Artifact deleted' });
});

// ---- Update Artifact (auth required) ----
artifactsRouter.patch('/:id', requireAuth, (req: AuthRequest, res) => {
  const { title, html, css, js } = req.body as Record<string, string>;

  const artifact = db.prepare(
    'SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?'
  ).get(req.params.id, req.userId!) as Record<string, unknown> | undefined;

  if (!artifact) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  const updates: string[] = [];
  const values: unknown[] = [];

  if (title !== undefined) { updates.push('title = ?'); values.push(title); }
  if (html !== undefined) { updates.push('html = ?'); values.push(html); }
  if (css !== undefined) { updates.push('css = ?'); values.push(css); }
  if (js !== undefined) { updates.push('js = ?'); values.push(js); }

  if (updates.length === 0) {
    res.status(400).json({ error: 'No fields to update' });
    return;
  }

  values.push(req.params.id);
  db.prepare(`UPDATE generated_artifacts SET ${updates.join(', ')} WHERE id = ?`).run(...values);

  const updated = db.prepare('SELECT * FROM generated_artifacts WHERE id = ?').get(req.params.id) as Record<string, unknown>;
  const baseUrl = `${req.protocol}://${req.get('host')}`;
  res.json({ ...updated, previewUrl: `${baseUrl}/preview/${req.userId}/${req.params.id}` });
});

// ---- Helpers ----

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function escapeJs(text: string): string {
  return text.replace(/'/g, "\\'").replace(/"/g, '\\"');
}

// ---- Custom Domain Management ----

artifactsRouter.post('/:id/domain', requireAuth, (req: AuthRequest, res) => {
  const { subdomain } = req.body as { subdomain?: string };
  const userId = req.userId!;
  const artifactId = req.params.id;

  if (!subdomain || !/^[a-z0-9-]+$/.test(subdomain) || subdomain.length < 2 || subdomain.length > 30) {
    res.status(400).json({ error: 'Invalid subdomain. Use 2-30 lowercase letters, numbers, and hyphens only.' });
    return;
  }

  // Check artifact exists and belongs to user
  const artifact = db.prepare('SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?').get(artifactId, userId);
  if (!artifact) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  // Check subdomain availability
  const existing = db.prepare('SELECT * FROM artifact_domains WHERE subdomain = ?').get(subdomain);
  if (existing) {
    res.status(409).json({ error: 'Subdomain already taken' });
    return;
  }

  // Remove any existing domain for this artifact
  db.prepare('DELETE FROM artifact_domains WHERE artifact_id = ?').run(artifactId);

  // Create new domain mapping
  const domainId = uuid();
  db.prepare(`
    INSERT INTO artifact_domains (id, artifact_id, user_id, subdomain, is_active)
    VALUES (?, ?, ?, ?, 1)
  `).run(domainId, artifactId, userId, subdomain);

  const baseUrl = `${req.protocol}://${req.get('host')}`;
  logger.info({ userId, artifactId, subdomain }, 'Custom domain assigned');

  res.json({
    success: true,
    subdomain,
    fullDomain: `${subdomain}.${req.get('host')}`,
    previewUrl: `${baseUrl}/preview/${userId}/${artifactId}`,
  });
});

artifactsRouter.delete('/:id/domain', requireAuth, (req: AuthRequest, res) => {
  const result = db.prepare('DELETE FROM artifact_domains WHERE artifact_id = ? AND user_id = ?').run(req.params.id, req.userId!);

  if (result.changes === 0) {
    res.status(404).json({ error: 'No custom domain found for this artifact' });
    return;
  }

  res.json({ success: true, message: 'Custom domain removed' });
});

artifactsRouter.get('/:id/domain', requireAuth, (req: AuthRequest, res) => {
  const domain = db.prepare('SELECT * FROM artifact_domains WHERE artifact_id = ? AND user_id = ?').get(req.params.id, req.userId!) as {
    subdomain: string;
    is_active: number;
    created_at: string;
  } | undefined;

  if (!domain) {
    res.status(404).json({ error: 'No custom domain found' });
    return;
  }

  res.json({
    subdomain: domain.subdomain,
    fullDomain: `${domain.subdomain}.${req.get('host')}`,
    isActive: domain.is_active === 1,
    createdAt: domain.created_at,
  });
});

// ---- Export Functionality ----

artifactsRouter.post('/:id/export/zip', requireAuth, async (req: AuthRequest, res) => {
  const artifact = db.prepare('SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?').get(req.params.id, req.userId!) as {
    title: string;
    html: string;
    css: string;
    js: string;
  } | undefined;

  if (!artifact) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  try {
    // Create a simple ZIP using Node.js built-in zlib
    const { createZipArchive } = await import('../services/export.js');
    const zipBuffer = await createZipArchive({
      'index.html': buildHtmlFile(artifact.title, artifact.html, artifact.css, artifact.js),
      'style.css': artifact.css || '',
      'script.js': artifact.js || '',
      'README.md': `# ${artifact.title}\n\nGenerated with Agentin`,
    });

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${artifact.title.replace(/\s+/g, '_')}.zip"`);
    res.send(zipBuffer);

    logger.info({ userId: req.userId, artifactId: req.params.id }, 'Artifact exported as ZIP');
  } catch (err) {
    logger.error({ err, artifactId: req.params.id }, 'ZIP export failed');
    res.status(500).json({ error: 'Export failed' });
  }
});

artifactsRouter.post('/:id/export/netlify', requireAuth, async (req: AuthRequest, res) => {
  const { netlifyToken } = req.body as { netlifyToken?: string };

  if (!netlifyToken) {
    res.status(400).json({ error: 'Netlify token required' });
    return;
  }

  const artifact = db.prepare('SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?').get(req.params.id, req.userId!) as {
    title: string;
    html: string;
    css: string;
    js: string;
  } | undefined;

  if (!artifact) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  try {
    const { deployToNetlify } = await import('../services/deploy.js');
    const result = await deployToNetlify(netlifyToken, {
      name: artifact.title,
      html: buildHtmlFile(artifact.title, artifact.html, artifact.css, artifact.js),
      css: artifact.css || '',
      js: artifact.js || '',
    });

    // Save deployment info
    db.prepare(`
      INSERT INTO artifact_deployments (id, artifact_id, user_id, provider, external_url, external_id, status)
      VALUES (?, ?, ?, 'netlify', ?, ?, 'active')
    `).run(uuid(), req.params.id, req.userId!, result.url, result.id);

    res.json({ success: true, url: result.url, message: `Deployed to Netlify: ${result.url}` });
  } catch (err) {
    logger.error({ err, artifactId: req.params.id }, 'Netlify deploy failed');
    res.status(500).json({ error: 'Deployment failed' });
  }
});

artifactsRouter.post('/:id/export/vercel', requireAuth, async (req: AuthRequest, res) => {
  const { vercelToken } = req.body as { vercelToken?: string };

  if (!vercelToken) {
    res.status(400).json({ error: 'Vercel token required' });
    return;
  }

  const artifact = db.prepare('SELECT * FROM generated_artifacts WHERE id = ? AND user_id = ?').get(req.params.id, req.userId!) as {
    title: string;
    html: string;
    css: string;
    js: string;
  } | undefined;

  if (!artifact) {
    res.status(404).json({ error: 'Artifact not found' });
    return;
  }

  try {
    const { deployToVercel } = await import('../services/deploy.js');
    const result = await deployToVercel(vercelToken, {
      name: artifact.title,
      html: buildHtmlFile(artifact.title, artifact.html, artifact.css, artifact.js),
      css: artifact.css || '',
      js: artifact.js || '',
    });

    // Save deployment info
    db.prepare(`
      INSERT INTO artifact_deployments (id, artifact_id, user_id, provider, external_url, external_id, status)
      VALUES (?, ?, ?, 'vercel', ?, ?, 'active')
    `).run(uuid(), req.params.id, req.userId!, result.url, result.id);

    res.json({ success: true, url: result.url, message: `Deployed to Vercel: ${result.url}` });
  } catch (err) {
    logger.error({ err, artifactId: req.params.id }, 'Vercel deploy failed');
    res.status(500).json({ error: 'Deployment failed' });
  }
});

artifactsRouter.get('/:id/deployments', requireAuth, (req: AuthRequest, res) => {
  const deployments = db.prepare(`
    SELECT id, provider, external_url, status, created_at
    FROM artifact_deployments
    WHERE artifact_id = ? AND user_id = ?
    ORDER BY created_at DESC
  `).all(req.params.id, req.userId!);

  res.json({ deployments });
});

// ---- Helper: Build complete HTML file ----

function buildHtmlFile(title: string, html: string, css: string, js: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  ${html || ''}
  <script src="script.js"></script>
</body>
</html>`;
}
