import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';

export const portfolioRouter = Router();

const portfolios: Record<string, Record<string, unknown>> = {
  alex: {
    userId: 'demo-1',
    headline: 'Full-stack Developer & AI Enthusiast',
    about: "Building tools that make life easier. I love coding, automation, and helping others learn. My agent can answer questions about my work, schedule, or just chat!",
    avatar: 'AC',
    location: 'San Francisco, CA',
    role: 'Senior Developer',
    company: 'TechCorp',
    skills: ['React', 'TypeScript', 'Node.js', 'Python', 'AI/ML', 'OpenClaw'],
    projects: [
      { name: 'AutoTask', description: 'AI-powered task automation', url: '#', tags: ['AI', 'Automation'], aiGenerated: false },
      { name: 'CodeSync', description: 'Real-time code collaboration', url: '#', tags: ['Collaboration', 'WebRTC'], aiGenerated: false },
      { name: 'NeuralChat', description: 'Conversational AI interface', url: '#', tags: ['AI', 'Chat'], aiGenerated: true },
    ],
    milestones: [
      { date: '2026-01-15', title: 'Joined GeekSpace', description: 'Started the AI OS journey', autoGenerated: true },
      { date: '2026-01-20', title: 'Connected Telegram', description: 'First integration active', autoGenerated: true },
      { date: '2026-02-01', title: 'First Automation', description: 'Created portfolio update automation', autoGenerated: true },
    ],
    social: { github: 'github.com/alexchen', twitter: 'twitter.com/alexchen', linkedin: 'linkedin.com/in/alexchen', website: 'alexchen.dev', email: 'alex@example.com' },
    layout: 'classic',
    agentEnabled: true,
    visibility: { showInDirectory: true, showAvatar: true, showLocation: true, showProjects: true, showActivity: true },
  },
  sarah: {
    userId: 'demo-2',
    headline: 'Product Designer & Creative Technologist',
    about: 'Designing experiences that delight.',
    avatar: 'SK',
    location: 'New York, NY',
    role: 'Lead Designer',
    company: 'DesignStudio',
    skills: ['UI/UX', 'Figma', 'Design Systems', 'React', 'Motion Design'],
    projects: [
      { name: 'DesignKit', description: 'Component library for startups', url: '#' },
      { name: 'FlowMap', description: 'User journey visualization tool', url: '#' },
    ],
    milestones: [],
    social: { github: 'github.com/sarahkim', twitter: 'twitter.com/sarahkim', linkedin: 'linkedin.com/in/sarahkim', email: 'sarah@example.com' },
    layout: 'classic',
    agentEnabled: true,
    visibility: { showInDirectory: true, showAvatar: true, showLocation: true, showProjects: true, showActivity: false },
  },
  marcus: {
    userId: 'demo-3',
    headline: 'Founder & Startup Advisor',
    about: 'Helping founders build the future. 10+ years in tech, 3 exits.',
    avatar: 'MW',
    location: 'Austin, TX',
    role: 'Founder',
    company: 'ConsultX',
    skills: ['Strategy', 'Fundraising', 'Product', 'Leadership', 'Growth'],
    projects: [
      { name: 'StartupOS', description: 'Founder operating system', url: '#' },
      { name: 'VentureMap', description: 'Investor relationship tracker', url: '#' },
    ],
    milestones: [],
    social: { twitter: 'twitter.com/marcuswright', linkedin: 'linkedin.com/in/marcuswright', website: 'marcuswright.co', email: 'marcus@example.com' },
    layout: 'timeline',
    agentEnabled: true,
    visibility: { showInDirectory: true, showAvatar: true, showLocation: true, showProjects: true, showActivity: true },
  },
};

portfolioRouter.get('/me', requireAuth, (_req, res) => {
  res.json(portfolios['alex']);
});

portfolioRouter.patch('/me', requireAuth, (req, res) => {
  Object.assign(portfolios['alex'], req.body);
  res.json(portfolios['alex']);
});

portfolioRouter.get('/:username', (req, res) => {
  const portfolio = portfolios[req.params.username];
  if (!portfolio) { res.status(404).json({ error: 'Portfolio not found' }); return; }
  res.json(portfolio);
});

portfolioRouter.post('/ai-edit', requireAuth, (req, res) => {
  // Stub: Would call OpenClaw to rewrite sections
  res.json({ ...portfolios['alex'], about: `[AI-edited] ${req.body.prompt}\n\n${(portfolios['alex'] as Record<string, unknown>).about}` });
});
