/**
 * Schema convergence test — verifies that running all migrations on a fresh
 * in-memory DB produces exactly the committed schema snapshot.
 *
 * If this test fails, either:
 *   (a) you added/changed a migration without regenerating the snapshot — run
 *       `npm run db:snapshot` from the server/ directory, then commit the diff.
 *   (b) you changed the snapshot without updating migrations — revert or fix.
 */
import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Database from 'better-sqlite3';
import { runMigrations } from '../migrate.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SNAPSHOT_PATH = path.join(__dirname, 'fixtures', 'schema.snapshot.sql');

function openMemoryDb(): Database.Database {
  const db = new Database(':memory:');
  db.pragma('foreign_keys = ON');
  return db;
}

function dumpSchema(db: Database.Database): string {
  const rows = db.prepare(`
    SELECT type, name, sql
    FROM sqlite_master
    WHERE name NOT LIKE 'sqlite_%'
      AND name != '_migrations'
    ORDER BY type DESC, name ASC
  `).all() as Array<{ type: string; name: string; sql: string }>;

  const header =
    `-- Schema snapshot generated by: npm run db:snapshot\n` +
    `-- Do not edit manually. Regenerate with: npm run db:snapshot\n` +
    `-- Tables and indexes ordered by (type DESC, name ASC)\n\n`;
  const body = rows.map(r => r.sql + ';').join('\n\n') + '\n';
  return header + body;
}

describe('migrations convergence', () => {
  it('schema after runMigrations() matches committed snapshot', () => {
    const db = openMemoryDb();
    runMigrations(db);

    const actual = dumpSchema(db);
    const expected = fs.readFileSync(SNAPSHOT_PATH, 'utf-8');

    if (actual !== expected) {
      const actualLines = actual.split('\n');
      const expectedLines = expected.split('\n');
      const maxLen = Math.max(actualLines.length, expectedLines.length);
      const diffs: string[] = [];
      for (let i = 0; i < maxLen; i++) {
        const a = actualLines[i] ?? '<missing>';
        const e = expectedLines[i] ?? '<missing>';
        if (a !== e) {
          diffs.push(`line ${i + 1}:\n  snapshot: ${e}\n  actual:   ${a}`);
          if (diffs.length >= 20) {
            diffs.push('... (truncated, first 20 diffs shown)');
            break;
          }
        }
      }
      throw new Error(
        `Schema has drifted from snapshot.\n\nRun \`npm run db:snapshot\` in server/ to regenerate.\n\nDiffs:\n${diffs.join('\n')}`
      );
    }

    expect(actual).toBe(expected);
  });

  it('snapshot file exists and is non-empty', () => {
    const stat = fs.statSync(SNAPSHOT_PATH);
    expect(stat.size).toBeGreaterThan(0);
  });

  it('deliberate drift is detected — adding a table not in migrations fails', () => {
    const db = openMemoryDb();
    runMigrations(db);
    db.exec(`CREATE TABLE IF NOT EXISTS _rogue_table (id TEXT PRIMARY KEY)`);

    const actual = dumpSchema(db);
    const expected = fs.readFileSync(SNAPSHOT_PATH, 'utf-8');

    expect(actual).not.toBe(expected);
    expect(actual).toContain('_rogue_table');
  });
});
