import { useState, useEffect } from 'react';
import {
  Save, Plus, Trash2, X, ExternalLink, Sparkles, Loader2,
  User, Code2, FolderGit2, Award, Share2, Bot
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { useAuthStore } from '@/stores/authStore';
import { portfolioService } from '@/services/api';
import type { Portfolio, PortfolioProject, PortfolioMilestone, PortfolioLayout } from '@/types';

const emptyProject: PortfolioProject = { name: '', description: '', url: '', tags: [] };
const emptyMilestone: PortfolioMilestone = { date: '', title: '', description: '', autoGenerated: false };

export function PortfolioPage() {
  const user = useAuthStore((s) => s.user);
  const [activeTab, setActiveTab] = useState('profile');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  // Portfolio state
  const [headline, setHeadline] = useState('');
  const [about, setAbout] = useState('');
  const [avatar, setAvatar] = useState('');
  const [layout, setLayout] = useState<PortfolioLayout>('classic');
  const [skills, setSkills] = useState<string[]>([]);
  const [projects, setProjects] = useState<PortfolioProject[]>([]);
  const [milestones, setMilestones] = useState<PortfolioMilestone[]>([]);
  const [social, setSocial] = useState<Portfolio['social']>({});

  // Inline form state
  const [newSkill, setNewSkill] = useState('');
  const [editingProject, setEditingProject] = useState<PortfolioProject | null>(null);
  const [editingProjectIdx, setEditingProjectIdx] = useState<number | null>(null);
  const [editingMilestone, setEditingMilestone] = useState<PortfolioMilestone | null>(null);
  const [editingMilestoneIdx, setEditingMilestoneIdx] = useState<number | null>(null);
  const [tagInput, setTagInput] = useState('');

  // AI Edit state
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiLoading, setAiLoading] = useState(false);

  // Load portfolio
  useEffect(() => {
    portfolioService.get()
      .then(({ data }) => {
        setHeadline(data.headline || '');
        setAbout(data.about || '');
        setAvatar(data.avatar || '');
        setLayout(data.layout || 'classic');
        setSkills(data.skills || []);
        setProjects(data.projects || []);
        setMilestones(data.milestones || []);
        setSocial(data.social || {});
      })
      .catch(() => setMessage({ type: 'error', text: 'Failed to load portfolio' }))
      .finally(() => setIsLoading(false));
  }, []);

  const showMessage = (type: 'success' | 'error', text: string) => {
    setMessage({ type, text });
    setTimeout(() => setMessage(null), 3000);
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const data = await portfolioService.update({ headline, about, avatar, layout, skills, projects, milestones, social });
      // Refresh from server response
      setHeadline(data.data.headline || '');
      setAbout(data.data.about || '');
      setAvatar(data.data.avatar || '');
      setLayout(data.data.layout || 'classic');
      setSkills(data.data.skills || []);
      setProjects(data.data.projects || []);
      setMilestones(data.data.milestones || []);
      setSocial(data.data.social || {});
      showMessage('success', 'Portfolio saved successfully');
    } catch {
      showMessage('error', 'Failed to save portfolio');
    } finally {
      setIsSaving(false);
    }
  };

  const addSkill = () => {
    const s = newSkill.trim();
    if (s && !skills.includes(s)) {
      setSkills([...skills, s]);
      setNewSkill('');
    }
  };

  const removeSkill = (skill: string) => {
    setSkills(skills.filter((s) => s !== skill));
  };

  const saveProject = () => {
    if (!editingProject || !editingProject.name.trim()) return;
    if (editingProjectIdx !== null) {
      const updated = [...projects];
      updated[editingProjectIdx] = editingProject;
      setProjects(updated);
    } else {
      setProjects([...projects, editingProject]);
    }
    setEditingProject(null);
    setEditingProjectIdx(null);
    setTagInput('');
  };

  const deleteProject = (idx: number) => {
    setProjects(projects.filter((_, i) => i !== idx));
  };

  const saveMilestone = () => {
    if (!editingMilestone || !editingMilestone.title.trim()) return;
    if (editingMilestoneIdx !== null) {
      const updated = [...milestones];
      updated[editingMilestoneIdx] = editingMilestone;
      setMilestones(updated);
    } else {
      setMilestones([...milestones, editingMilestone]);
    }
    setEditingMilestone(null);
    setEditingMilestoneIdx(null);
  };

  const deleteMilestone = (idx: number) => {
    setMilestones(milestones.filter((_, i) => i !== idx));
  };

  const handleAiEdit = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    try {
      const { data } = await portfolioService.aiEdit(aiPrompt);
      setHeadline(data.headline || '');
      setAbout(data.about || '');
      setAvatar(data.avatar || '');
      setLayout(data.layout || 'classic');
      setSkills(data.skills || []);
      setProjects(data.projects || []);
      setMilestones(data.milestones || []);
      setSocial(data.social || {});
      setAiPrompt('');
      showMessage('success', 'AI edits applied — review and save when ready');
    } catch {
      showMessage('error', 'AI edit failed — try again');
    } finally {
      setAiLoading(false);
    }
  };

  const addTag = () => {
    const t = tagInput.trim();
    if (t && editingProject && !(editingProject.tags || []).includes(t)) {
      setEditingProject({ ...editingProject, tags: [...(editingProject.tags || []), t] });
      setTagInput('');
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="w-8 h-8 border-2 border-[#7B61FF] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl md:text-4xl font-bold mb-1" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
            Portfolio
          </h1>
          <p className="text-[#A7ACB8]">Manage your public portfolio</p>
        </div>
        <div className="flex items-center gap-3">
          {user?.username && (
            <a
              href={`/portfolio/${user.username}`}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-3 py-2 rounded-xl text-sm text-[#7B61FF] border border-[#7B61FF]/30 hover:bg-[#7B61FF]/10 transition-colors"
            >
              <ExternalLink className="w-4 h-4" />
              View Live
            </a>
          )}
          <Button onClick={handleSave} disabled={isSaving} className="bg-[#7B61FF] hover:bg-[#6B51EF]">
            {isSaving ? (
              <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin mr-2" />Saving...</>
            ) : (
              <><Save className="w-4 h-4 mr-2" />Save Changes</>
            )}
          </Button>
        </div>
      </div>

      {/* Status message */}
      {message && (
        <div className={`px-4 py-3 rounded-xl text-sm flex items-center gap-2 ${
          message.type === 'success'
            ? 'bg-[#61FF7B]/10 border border-[#61FF7B]/30 text-[#61FF7B]'
            : 'bg-[#FF6161]/10 border border-[#FF6161]/30 text-[#FF6161]'
        }`}>
          {message.text}
        </div>
      )}

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <TabsList className="bg-[#0B0B10] border border-[#7B61FF]/20 p-1 flex-wrap">
          <TabsTrigger value="profile" className="data-[state=active]:bg-[#7B61FF] data-[state=active]:text-white">
            <User className="w-4 h-4 mr-2" />Profile
          </TabsTrigger>
          <TabsTrigger value="skills" className="data-[state=active]:bg-[#7B61FF] data-[state=active]:text-white">
            <Code2 className="w-4 h-4 mr-2" />Skills
          </TabsTrigger>
          <TabsTrigger value="projects" className="data-[state=active]:bg-[#7B61FF] data-[state=active]:text-white">
            <FolderGit2 className="w-4 h-4 mr-2" />Projects
          </TabsTrigger>
          <TabsTrigger value="milestones" className="data-[state=active]:bg-[#7B61FF] data-[state=active]:text-white">
            <Award className="w-4 h-4 mr-2" />Milestones
          </TabsTrigger>
          <TabsTrigger value="social" className="data-[state=active]:bg-[#7B61FF] data-[state=active]:text-white">
            <Share2 className="w-4 h-4 mr-2" />Social
          </TabsTrigger>
          <TabsTrigger value="ai" className="data-[state=active]:bg-[#7B61FF] data-[state=active]:text-white">
            <Bot className="w-4 h-4 mr-2" />AI Edit
          </TabsTrigger>
        </TabsList>

        {/* ── Profile Tab ─────────────────────────────────────── */}
        <TabsContent value="profile" className="space-y-6">
          <Card className="bg-[#0B0B10] border-[#7B61FF]/20">
            <CardHeader>
              <CardTitle>Profile Details</CardTitle>
              <CardDescription className="text-[#A7ACB8]">Your public portfolio headline, bio, and layout</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <label className="text-sm text-[#A7ACB8] mb-2 block">Headline</label>
                <Input
                  value={headline}
                  onChange={(e) => setHeadline(e.target.value)}
                  placeholder="Full-Stack Developer & AI Enthusiast"
                  className="bg-[#05050A] border-[#7B61FF]/30 text-[#F4F6FF]"
                />
              </div>
              <div>
                <label className="text-sm text-[#A7ACB8] mb-2 block">Bio</label>
                <textarea
                  value={about}
                  onChange={(e) => setAbout(e.target.value)}
                  placeholder="Tell visitors about yourself..."
                  className="w-full p-3 rounded-xl bg-[#05050A] border border-[#7B61FF]/30 text-[#F4F6FF] min-h-[120px] resize-none focus:outline-none focus:border-[#7B61FF]"
                />
              </div>
              <div>
                <label className="text-sm text-[#A7ACB8] mb-2 block">Avatar URL</label>
                <Input
                  value={avatar}
                  onChange={(e) => setAvatar(e.target.value)}
                  placeholder="https://example.com/avatar.jpg or initials"
                  className="bg-[#05050A] border-[#7B61FF]/30 text-[#F4F6FF]"
                />
              </div>
              <div>
                <label className="text-sm text-[#A7ACB8] mb-3 block">Layout</label>
                <div className="flex gap-3">
                  {(['classic', 'timeline', 'grid'] as PortfolioLayout[]).map((l) => (
                    <button
                      key={l}
                      onClick={() => setLayout(l)}
                      className={`flex-1 p-4 rounded-xl border-2 capitalize transition-all ${
                        layout === l
                          ? 'border-[#7B61FF] bg-[#7B61FF]/10 text-[#7B61FF]'
                          : 'border-[#7B61FF]/20 text-[#A7ACB8] hover:border-[#7B61FF]/40'
                      }`}
                    >
                      {l}
                    </button>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Skills Tab ──────────────────────────────────────── */}
        <TabsContent value="skills" className="space-y-6">
          <Card className="bg-[#0B0B10] border-[#7B61FF]/20">
            <CardHeader>
              <CardTitle>Skills</CardTitle>
              <CardDescription className="text-[#A7ACB8]">Add technologies and skills you want to showcase</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <Input
                  value={newSkill}
                  onChange={(e) => setNewSkill(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && addSkill()}
                  placeholder="e.g. TypeScript, React, Docker..."
                  className="bg-[#05050A] border-[#7B61FF]/30 text-[#F4F6FF]"
                />
                <Button onClick={addSkill} disabled={!newSkill.trim()} className="bg-[#7B61FF] hover:bg-[#6B51EF]">
                  <Plus className="w-4 h-4 mr-2" />Add
                </Button>
              </div>

              {skills.length === 0 ? (
                <div className="text-center py-8">
                  <Code2 className="w-10 h-10 text-[#7B61FF]/30 mx-auto mb-3" />
                  <p className="text-[#A7ACB8]">No skills added yet</p>
                </div>
              ) : (
                <div className="flex flex-wrap gap-2">
                  {skills.map((skill) => (
                    <button
                      key={skill}
                      onClick={() => removeSkill(skill)}
                      className="group flex items-center gap-1.5 px-4 py-2 rounded-full bg-[#7B61FF]/10 border border-[#7B61FF]/30 text-[#7B61FF] hover:bg-[#FF6161]/10 hover:border-[#FF6161]/30 hover:text-[#FF6161] transition-all"
                    >
                      {skill}
                      <X className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-opacity" />
                    </button>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Projects Tab ────────────────────────────────────── */}
        <TabsContent value="projects" className="space-y-6">
          <Card className="bg-[#0B0B10] border-[#7B61FF]/20">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Projects</CardTitle>
                  <CardDescription className="text-[#A7ACB8]">Showcase your best work</CardDescription>
                </div>
                <Button
                  onClick={() => { setEditingProject({ ...emptyProject }); setEditingProjectIdx(null); }}
                  className="bg-[#7B61FF] hover:bg-[#6B51EF]"
                >
                  <Plus className="w-4 h-4 mr-2" />Add Project
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Inline project form */}
              {editingProject && (
                <div className="p-4 rounded-xl bg-[#05050A] border border-[#7B61FF]/30 space-y-3">
                  <div className="grid md:grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm text-[#A7ACB8] mb-1 block">Name *</label>
                      <Input
                        value={editingProject.name}
                        onChange={(e) => setEditingProject({ ...editingProject, name: e.target.value })}
                        placeholder="Project name"
                        className="bg-[#0B0B10] border-[#7B61FF]/30 text-[#F4F6FF]"
                      />
                    </div>
                    <div>
                      <label className="text-sm text-[#A7ACB8] mb-1 block">URL</label>
                      <Input
                        value={editingProject.url}
                        onChange={(e) => setEditingProject({ ...editingProject, url: e.target.value })}
                        placeholder="https://..."
                        className="bg-[#0B0B10] border-[#7B61FF]/30 text-[#F4F6FF]"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="text-sm text-[#A7ACB8] mb-1 block">Description</label>
                    <textarea
                      value={editingProject.description}
                      onChange={(e) => setEditingProject({ ...editingProject, description: e.target.value })}
                      placeholder="What does this project do?"
                      className="w-full p-3 rounded-xl bg-[#0B0B10] border border-[#7B61FF]/30 text-[#F4F6FF] min-h-[80px] resize-none focus:outline-none focus:border-[#7B61FF]"
                    />
                  </div>
                  <div>
                    <label className="text-sm text-[#A7ACB8] mb-1 block">Tags</label>
                    <div className="flex gap-2 mb-2">
                      <Input
                        value={tagInput}
                        onChange={(e) => setTagInput(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addTag())}
                        placeholder="Add tag..."
                        className="bg-[#0B0B10] border-[#7B61FF]/30 text-[#F4F6FF]"
                      />
                      <Button onClick={addTag} variant="outline" className="border-[#7B61FF]/30">
                        <Plus className="w-4 h-4" />
                      </Button>
                    </div>
                    {(editingProject.tags || []).length > 0 && (
                      <div className="flex flex-wrap gap-1">
                        {editingProject.tags!.map((tag) => (
                          <Badge
                            key={tag}
                            variant="outline"
                            className="border-[#7B61FF]/30 text-[#A7ACB8] cursor-pointer hover:border-[#FF6161]/30 hover:text-[#FF6161]"
                            onClick={() => setEditingProject({ ...editingProject, tags: editingProject.tags!.filter((t) => t !== tag) })}
                          >
                            {tag} <X className="w-3 h-3 ml-1" />
                          </Badge>
                        ))}
                      </div>
                    )}
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" onClick={() => { setEditingProject(null); setEditingProjectIdx(null); setTagInput(''); }} className="border-[#7B61FF]/30">
                      Cancel
                    </Button>
                    <Button onClick={saveProject} disabled={!editingProject.name.trim()} className="bg-[#7B61FF] hover:bg-[#6B51EF]">
                      {editingProjectIdx !== null ? 'Update' : 'Add'}
                    </Button>
                  </div>
                </div>
              )}

              {projects.length === 0 && !editingProject && (
                <div className="text-center py-8">
                  <FolderGit2 className="w-10 h-10 text-[#7B61FF]/30 mx-auto mb-3" />
                  <p className="text-[#A7ACB8]">No projects yet</p>
                </div>
              )}

              {projects.map((project, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-[#05050A] border border-[#7B61FF]/20 group hover:border-[#7B61FF]/40 transition-all">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h3 className="font-semibold text-[#F4F6FF]">{project.name}</h3>
                      {project.description && <p className="text-sm text-[#A7ACB8] mt-1">{project.description}</p>}
                      {project.url && <p className="text-xs text-[#7B61FF] mt-1 truncate">{project.url}</p>}
                      {(project.tags || []).length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-2">
                          {project.tags!.map((tag) => (
                            <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-[#0B0B10] text-[#A7ACB8]">{tag}</span>
                          ))}
                        </div>
                      )}
                    </div>
                    <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => { setEditingProject({ ...project }); setEditingProjectIdx(idx); }}
                        className="text-[#7B61FF] hover:text-[#7B61FF]"
                      >
                        Edit
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => deleteProject(idx)}
                        className="text-[#FF6161] hover:text-[#FF6161]"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Milestones Tab ──────────────────────────────────── */}
        <TabsContent value="milestones" className="space-y-6">
          <Card className="bg-[#0B0B10] border-[#7B61FF]/20">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Milestones</CardTitle>
                  <CardDescription className="text-[#A7ACB8]">Key achievements and career highlights</CardDescription>
                </div>
                <Button
                  onClick={() => { setEditingMilestone({ ...emptyMilestone }); setEditingMilestoneIdx(null); }}
                  className="bg-[#7B61FF] hover:bg-[#6B51EF]"
                >
                  <Plus className="w-4 h-4 mr-2" />Add Milestone
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Inline milestone form */}
              {editingMilestone && (
                <div className="p-4 rounded-xl bg-[#05050A] border border-[#7B61FF]/30 space-y-3">
                  <div className="grid md:grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm text-[#A7ACB8] mb-1 block">Title *</label>
                      <Input
                        value={editingMilestone.title}
                        onChange={(e) => setEditingMilestone({ ...editingMilestone, title: e.target.value })}
                        placeholder="e.g. Launched SaaS product"
                        className="bg-[#0B0B10] border-[#7B61FF]/30 text-[#F4F6FF]"
                      />
                    </div>
                    <div>
                      <label className="text-sm text-[#A7ACB8] mb-1 block">Date</label>
                      <Input
                        value={editingMilestone.date}
                        onChange={(e) => setEditingMilestone({ ...editingMilestone, date: e.target.value })}
                        placeholder="2025-01 or Jan 2025"
                        className="bg-[#0B0B10] border-[#7B61FF]/30 text-[#F4F6FF]"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="text-sm text-[#A7ACB8] mb-1 block">Description</label>
                    <textarea
                      value={editingMilestone.description}
                      onChange={(e) => setEditingMilestone({ ...editingMilestone, description: e.target.value })}
                      placeholder="What happened and why it matters"
                      className="w-full p-3 rounded-xl bg-[#0B0B10] border border-[#7B61FF]/30 text-[#F4F6FF] min-h-[80px] resize-none focus:outline-none focus:border-[#7B61FF]"
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" onClick={() => { setEditingMilestone(null); setEditingMilestoneIdx(null); }} className="border-[#7B61FF]/30">
                      Cancel
                    </Button>
                    <Button onClick={saveMilestone} disabled={!editingMilestone.title.trim()} className="bg-[#7B61FF] hover:bg-[#6B51EF]">
                      {editingMilestoneIdx !== null ? 'Update' : 'Add'}
                    </Button>
                  </div>
                </div>
              )}

              {milestones.length === 0 && !editingMilestone && (
                <div className="text-center py-8">
                  <Award className="w-10 h-10 text-[#7B61FF]/30 mx-auto mb-3" />
                  <p className="text-[#A7ACB8]">No milestones yet</p>
                </div>
              )}

              {/* Timeline-style list */}
              <div className="space-y-0">
                {milestones.map((milestone, idx) => (
                  <div key={idx} className="flex gap-4 group">
                    <div className="flex flex-col items-center">
                      <div className="w-3 h-3 rounded-full bg-[#7B61FF] mt-1.5" />
                      {idx < milestones.length - 1 && <div className="w-0.5 flex-1 bg-[#7B61FF]/20" />}
                    </div>
                    <div className="flex-1 pb-6">
                      <div className="flex items-start justify-between">
                        <div>
                          <div className="text-xs text-[#7B61FF] font-mono mb-1">{milestone.date}</div>
                          <div className="font-medium text-[#F4F6FF]">{milestone.title}</div>
                          {milestone.description && <div className="text-sm text-[#A7ACB8] mt-1">{milestone.description}</div>}
                        </div>
                        <div className="flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => { setEditingMilestone({ ...milestone }); setEditingMilestoneIdx(idx); }}
                            className="text-[#7B61FF] hover:text-[#7B61FF]"
                          >
                            Edit
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => deleteMilestone(idx)}
                            className="text-[#FF6161] hover:text-[#FF6161]"
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Social Links Tab ────────────────────────────────── */}
        <TabsContent value="social" className="space-y-6">
          <Card className="bg-[#0B0B10] border-[#7B61FF]/20">
            <CardHeader>
              <CardTitle>Social Links</CardTitle>
              <CardDescription className="text-[#A7ACB8]">Connect your online presence — all fields are optional</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {([
                { key: 'github' as const, label: 'GitHub', placeholder: 'github.com/username' },
                { key: 'twitter' as const, label: 'Twitter / X', placeholder: 'x.com/username' },
                { key: 'linkedin' as const, label: 'LinkedIn', placeholder: 'linkedin.com/in/username' },
                { key: 'website' as const, label: 'Website', placeholder: 'yoursite.com' },
                { key: 'email' as const, label: 'Email', placeholder: 'you@example.com' },
              ]).map((field) => (
                <div key={field.key}>
                  <label className="text-sm text-[#A7ACB8] mb-2 block">{field.label}</label>
                  <Input
                    value={social[field.key] || ''}
                    onChange={(e) => setSocial({ ...social, [field.key]: e.target.value })}
                    placeholder={field.placeholder}
                    className="bg-[#05050A] border-[#7B61FF]/30 text-[#F4F6FF]"
                  />
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── AI Edit Tab ─────────────────────────────────────── */}
        <TabsContent value="ai" className="space-y-6">
          <Card className="bg-[#0B0B10] border-[#7B61FF]/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-[#7B61FF]" />
                AI Portfolio Editor
              </CardTitle>
              <CardDescription className="text-[#A7ACB8]">
                Describe changes in plain English and let AI update your portfolio
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <textarea
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="e.g. Make my bio more professional, add a React project, rewrite my headline to focus on AI engineering..."
                className="w-full p-4 rounded-xl bg-[#05050A] border border-[#7B61FF]/30 text-[#F4F6FF] min-h-[140px] resize-none focus:outline-none focus:border-[#7B61FF]"
              />
              <Button
                onClick={handleAiEdit}
                disabled={aiLoading || !aiPrompt.trim()}
                className="bg-[#7B61FF] hover:bg-[#6B51EF] w-full"
              >
                {aiLoading ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Applying...</>
                ) : (
                  <><Sparkles className="w-4 h-4 mr-2" />Apply AI Edit</>
                )}
              </Button>
              <p className="text-xs text-[#A7ACB8] text-center">
                Changes are applied locally — review them in the other tabs, then click Save Changes to persist.
              </p>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
