import { useState, useEffect } from 'react';
import {
  Save, Plus, Trash2, X, ExternalLink, Sparkles, Loader2,
  User, Code2, FolderGit2, Award, Share2, Bot, Wand2, Lightbulb, CheckCircle2,
  BarChart3, Eye, MousePointer, TrendingUp, Globe
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { useAuthStore } from '@/stores/authStore';
import { portfolioService } from '@/services/api';
import type { Portfolio, PortfolioProject, PortfolioMilestone, PortfolioLayout } from '@/types';

const emptyProject: PortfolioProject = { name: '', description: '', url: '', tags: [] };
const emptyMilestone: PortfolioMilestone = { date: '', title: '', description: '', autoGenerated: false };

export function PortfolioPage() {
  const user = useAuthStore((s) => s.user);
  const [activeTab, setActiveTab] = useState('profile');
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [linkCopied, setLinkCopied] = useState(false);

  const handleCopyLink = async () => {
    if (!user?.username) return;
    const url = `${window.location.origin}/portfolio/${user.username}`;
    try {
      await navigator.clipboard.writeText(url);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    } catch {
      // Fallback: show the URL in message
      setMessage({ type: 'success', text: `Share this link: ${url}` });
    }
  };

  // Portfolio state
  const [headline, setHeadline] = useState('');
  const [about, setAbout] = useState('');
  const [avatar, setAvatar] = useState('');
  const [layout, setLayout] = useState<PortfolioLayout>('classic');
  const [skills, setSkills] = useState<string[]>([]);
  const [projects, setProjects] = useState<PortfolioProject[]>([]);
  const [milestones, setMilestones] = useState<PortfolioMilestone[]>([]);
  const [social, setSocial] = useState<Portfolio['social']>({});

  // Inline form state
  const [newSkill, setNewSkill] = useState('');
  const [editingProject, setEditingProject] = useState<PortfolioProject | null>(null);
  const [editingProjectIdx, setEditingProjectIdx] = useState<number | null>(null);
  const [editingMilestone, setEditingMilestone] = useState<PortfolioMilestone | null>(null);
  const [editingMilestoneIdx, setEditingMilestoneIdx] = useState<number | null>(null);
  const [tagInput, setTagInput] = useState('');

  // AI Edit state
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiLoading, setAiLoading] = useState(false);

  // Portfolio visit stats
  const [portfolioStats, setPortfolioStats] = useState<{ totalViews: number; recentViews: number } | null>(null);

  // Magic Generate state
  const [generatingField, setGeneratingField] = useState<string | null>(null);
  const [generatedPreview, setGeneratedPreview] = useState<string | null>(null);
  const [generateTarget, setGenerateTarget] = useState<{ field: string; setter: (val: string) => void } | null>(null);

  // Suggestions state
  const [suggestions, setSuggestions] = useState<Array<{
    id: string;
    field: string;
    currentValue: string;
    suggestedValue: string;
    reason: string;
    confidence: number;
  }>>([]);
  const [loadingSuggestions, setLoadingSuggestions] = useState(false);
  const [applyingSuggestion, setApplyingSuggestion] = useState<string | null>(null);

  // Load portfolio and suggestions
  useEffect(() => {
    portfolioService.get()
      .then(({ data }) => {
        setHeadline(data.headline || '');
        setAbout(data.about || '');
        setAvatar(data.avatar || '');
        setLayout(data.layout || 'classic');
        setSkills(data.skills || []);
        setProjects(data.projects || []);
        setMilestones(data.milestones || []);
        setSocial(data.social || {});
      })
      .catch(() => setMessage({ type: 'error', text: 'Failed to load portfolio' }))
      .finally(() => setIsLoading(false));

    // Load suggestions
    loadSuggestions();

    // Load portfolio visit stats
    portfolioService.getStats()
      .then(({ data }) => setPortfolioStats(data))
      .catch(() => { /* non-fatal */ });
  }, []);

  const loadSuggestions = async () => {
    setLoadingSuggestions(true);
    try {
      const { data } = await portfolioService.getSuggestions();
      setSuggestions(data);
    } catch {
      // Silent fail - suggestions are optional
    } finally {
      setLoadingSuggestions(false);
    }
  };

  const showMessage = (type: 'success' | 'error', text: string) => {
    setMessage({ type, text });
    setTimeout(() => setMessage(null), 3000);
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const data = await portfolioService.update({ headline, about, avatar, layout, skills, projects, milestones, social });
      // Refresh from server response
      setHeadline(data.data.headline || '');
      setAbout(data.data.about || '');
      setAvatar(data.data.avatar || '');
      setLayout(data.data.layout || 'classic');
      setSkills(data.data.skills || []);
      setProjects(data.data.projects || []);
      setMilestones(data.data.milestones || []);
      setSocial(data.data.social || {});
      showMessage('success', 'Portfolio saved successfully');
    } catch {
      showMessage('error', 'Failed to save portfolio');
    } finally {
      setIsSaving(false);
    }
  };

  const addSkill = () => {
    const s = newSkill.trim();
    if (s && !skills.includes(s)) {
      setSkills([...skills, s]);
      setNewSkill('');
    }
  };

  const removeSkill = (skill: string) => {
    setSkills(skills.filter((s) => s !== skill));
  };

  const saveProject = () => {
    if (!editingProject || !editingProject.name.trim()) return;
    if (editingProjectIdx !== null) {
      const updated = [...projects];
      updated[editingProjectIdx] = editingProject;
      setProjects(updated);
    } else {
      setProjects([...projects, editingProject]);
    }
    setEditingProject(null);
    setEditingProjectIdx(null);
    setTagInput('');
  };

  const deleteProject = (idx: number) => {
    setProjects(projects.filter((_, i) => i !== idx));
  };

  const saveMilestone = () => {
    if (!editingMilestone || !editingMilestone.title.trim()) return;
    if (editingMilestoneIdx !== null) {
      const updated = [...milestones];
      updated[editingMilestoneIdx] = editingMilestone;
      setMilestones(updated);
    } else {
      setMilestones([...milestones, editingMilestone]);
    }
    setEditingMilestone(null);
    setEditingMilestoneIdx(null);
  };

  const deleteMilestone = (idx: number) => {
    setMilestones(milestones.filter((_, i) => i !== idx));
  };

  const handleAiEdit = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    try {
      const { data } = await portfolioService.aiEdit(aiPrompt);
      setHeadline(data.headline || '');
      setAbout(data.about || '');
      setAvatar(data.avatar || '');
      setLayout(data.layout || 'classic');
      setSkills(data.skills || []);
      setProjects(data.projects || []);
      setMilestones(data.milestones || []);
      setSocial(data.social || {});
      setAiPrompt('');
      showMessage('success', 'AI edits applied — review and save when ready');
    } catch {
      showMessage('error', 'AI edit failed — try again');
    } finally {
      setAiLoading(false);
    }
  };

  // Magic Generate handlers
  const handleGenerate = async (field: string, context: string, setter: (val: string) => void) => {
    setGeneratingField(field);
    setGenerateTarget({ field, setter });
    try {
      const { data } = await portfolioService.generateField(field, context);
      setGeneratedPreview(data.generated);
      showMessage('success', `Generated ${field} (5 credits used)`);
    } catch (err: unknown) {
      const error = err as { response?: { status?: number; data?: { error?: string } } };
      if (error.response?.status === 402) {
        showMessage('error', 'Insufficient credits — upgrade your plan');
      } else {
        showMessage('error', error.response?.data?.error || 'Generation failed');
      }
    } finally {
      setGeneratingField(null);
    }
  };

  const applyGenerated = () => {
    if (generatedPreview && generateTarget) {
      generateTarget.setter(generatedPreview);
      setGeneratedPreview(null);
      setGenerateTarget(null);
      showMessage('success', 'Generated content applied — save to persist');
    }
  };

  const discardGenerated = () => {
    setGeneratedPreview(null);
    setGenerateTarget(null);
  };

  // Suggestions handlers
  const handleApplySuggestion = async (suggestionId: string) => {
    setApplyingSuggestion(suggestionId);
    try {
      await portfolioService.applySuggestion(suggestionId);
      // Refresh portfolio data
      const { data } = await portfolioService.get();
      setHeadline(data.headline || '');
      setAbout(data.about || '');
      setSkills(data.skills || []);
      setProjects(data.projects || []);
      setMilestones(data.milestones || []);
      // Remove applied suggestion
      setSuggestions(suggestions.filter(s => s.id !== suggestionId));
      showMessage('success', 'Suggestion applied — save to persist');
    } catch {
      showMessage('error', 'Failed to apply suggestion');
    } finally {
      setApplyingSuggestion(null);
    }
  };

  const addTag = () => {
    const t = tagInput.trim();
    if (t && editingProject && !(editingProject.tags || []).includes(t)) {
      setEditingProject({ ...editingProject, tags: [...(editingProject.tags || []), t] });
      setTagInput('');
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <div className="w-8 h-8 border-2 border-[#00F0FF] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl md:text-4xl font-bold mb-1" style={{ fontFamily: 'Syne, sans-serif' }}>
            Portfolio
          </h1>
          <p className="text-[#6B7280]">Manage your public portfolio</p>
          {portfolioStats !== null && (
            <p className="text-xs text-[#6B7280] mt-1">
              <Eye className="w-3 h-3 inline mr-1 text-[#00F0FF]" />
              {portfolioStats.totalViews} total views · {portfolioStats.recentViews} this week
            </p>
          )}
        </div>
        <div className="flex items-center gap-3">
          {user?.username && (
            <>
              <button
                onClick={handleCopyLink}
                className="inline-flex items-center gap-2 px-3 py-2 rounded-xl text-sm border transition-colors min-h-[36px]"
                style={linkCopied ? { color: '#00FF88', borderColor: 'rgba(0,255,136,0.4)', background: 'rgba(0,255,136,0.1)' } : { color: '#BF5FFF', borderColor: 'rgba(191,95,255,0.3)' }}
                title="Copy portfolio link"
              >
                <Share2 className="w-4 h-4" />
                {linkCopied ? 'Copied!' : 'Copy Link'}
              </button>
              <a
                href={`/portfolio/${user.username}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-3 py-2 rounded-xl text-sm text-[#00F0FF] border border-[#00F0FF]/30 hover:bg-[#00F0FF]/10 transition-colors"
              >
                <ExternalLink className="w-4 h-4" />
                View Live
              </a>
            </>
          )}
          <Button onClick={handleSave} disabled={isSaving} className="bg-[#00F0FF] hover:bg-[#00D4B0] press-scale">
            {isSaving ? (
              <><div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin mr-2" />Saving...</>
            ) : (
              <><Save className="w-4 h-4 mr-2" />Save Changes</>
            )}
          </Button>
        </div>
      </div>

      {/* Status message */}
      {message && (
        <div className={`px-4 py-3 rounded-xl text-sm flex items-center gap-2 ${
          message.type === 'success'
            ? 'bg-[#00FF88]/10 border border-[#00FF88]/30 text-[#00FF88]'
            : 'bg-[#FF6161]/10 border border-[#FF6161]/30 text-[#FF6161]'
        }`}>
          {message.text}
        </div>
      )}

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-6">
        <div className="overflow-x-auto -mx-1 px-1 scrollbar-hide">
          <TabsList className="bg-[#0C0C18] border border-[#00F0FF]/20 p-1 flex flex-nowrap w-max md:w-auto">
            <TabsTrigger value="profile" data-testid="portfolio-tab-profile" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <User className="w-4 h-4 mr-2" />Profile
            </TabsTrigger>
            <TabsTrigger value="skills" data-testid="portfolio-tab-skills" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <Code2 className="w-4 h-4 mr-2" />Skills
            </TabsTrigger>
            <TabsTrigger value="projects" data-testid="portfolio-tab-projects" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <FolderGit2 className="w-4 h-4 mr-2" />Projects
            </TabsTrigger>
            <TabsTrigger value="milestones" data-testid="portfolio-tab-milestones" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <Award className="w-4 h-4 mr-2" />Milestones
            </TabsTrigger>
            <TabsTrigger value="social" data-testid="portfolio-tab-social" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <Share2 className="w-4 h-4 mr-2" />Social
            </TabsTrigger>
            <TabsTrigger value="ai" data-testid="portfolio-tab-ai" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <Bot className="w-4 h-4 mr-2" />AI Edit
            </TabsTrigger>
            <TabsTrigger value="suggestions" data-testid="portfolio-tab-suggestions" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <Lightbulb className="w-4 h-4 mr-2" />Suggestions
              {suggestions.length > 0 && (
                <span className="ml-1.5 px-1.5 py-0.5 text-xs bg-[#FF6161] text-white rounded-full">
                  {suggestions.length}
                </span>
              )}
            </TabsTrigger>
            <TabsTrigger value="analytics" data-testid="portfolio-tab-analytics" className="data-[state=active]:bg-[#00F0FF] data-[state=active]:text-white whitespace-nowrap press-scale">
              <BarChart3 className="w-4 h-4 mr-2" />Analytics
            </TabsTrigger>
          </TabsList>
        </div>

        {/* ── Profile Tab ─────────────────────────────────────── */}
        <TabsContent value="profile" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <CardTitle>Profile Details</CardTitle>
              <CardDescription className="text-[#6B7280]">Your public portfolio headline, bio, and layout</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-sm text-[#6B7280] block">Headline</label>
                  <button
                    onClick={() => handleGenerate('headline', `${about}\n${skills.join(', ')}`, setHeadline)}
                    disabled={generatingField === 'headline'}
                    className="text-xs flex items-center gap-1 text-[#00F0FF] hover:text-[#00D4B0] disabled:opacity-50"
                  >
                    {generatingField === 'headline' ? (
                      <Loader2 className="w-3 h-3 animate-spin" />
                    ) : (
                      <Wand2 className="w-3 h-3" />
                    )}
                    Generate
                  </button>
                </div>
                <Input
                  value={headline}
                  onChange={(e) => setHeadline(e.target.value)}
                  placeholder="Full-Stack Developer & AI Enthusiast"
                  className="bg-[#06060B] border-[#00F0FF]/30 text-[#E8E8F0]"
                />
              </div>
              <div>
                <div className="flex items-center justify-between mb-2">
                  <label className="text-sm text-[#6B7280] block">Bio</label>
                  <button
                    onClick={() => handleGenerate('about', `${headline}\n${skills.join(', ')}`, setAbout)}
                    disabled={generatingField === 'about'}
                    className="text-xs flex items-center gap-1 text-[#00F0FF] hover:text-[#00D4B0] disabled:opacity-50"
                  >
                    {generatingField === 'about' ? (
                      <Loader2 className="w-3 h-3 animate-spin" />
                    ) : (
                      <Wand2 className="w-3 h-3" />
                    )}
                    Generate
                  </button>
                </div>
                <textarea
                  value={about}
                  onChange={(e) => setAbout(e.target.value)}
                  placeholder="Tell visitors about yourself..."
                  className="w-full p-3 rounded-xl bg-[#06060B] border border-[#00F0FF]/30 text-[#E8E8F0] min-h-[120px] resize-none focus:outline-none focus:border-[#00F0FF]"
                />
              </div>
              <div>
                <label className="text-sm text-[#6B7280] mb-2 block">Avatar URL</label>
                <Input
                  value={avatar}
                  onChange={(e) => setAvatar(e.target.value)}
                  placeholder="https://example.com/avatar.jpg or initials"
                  className="bg-[#06060B] border-[#00F0FF]/30 text-[#E8E8F0]"
                />
              </div>
              <div>
                <label className="text-sm text-[#6B7280] mb-3 block">Layout</label>
                <div className="flex gap-3">
                  {(['classic', 'timeline', 'grid'] as PortfolioLayout[]).map((l) => (
                    <button
                      key={l}
                      onClick={() => setLayout(l)}
                      className={`flex-1 p-4 min-h-[44px] rounded-xl border-2 capitalize transition-all press-scale ${
                        layout === l
                          ? 'border-[#00F0FF] bg-[#00F0FF]/10 text-[#00F0FF]'
                          : 'border-[#00F0FF]/20 text-[#6B7280] hover:border-[#00F0FF]/40'
                      }`}
                    >
                      {l}
                    </button>
                  ))}
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Skills Tab ──────────────────────────────────────── */}
        <TabsContent value="skills" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Skills</CardTitle>
                  <CardDescription className="text-[#6B7280]">Add technologies and skills you want to showcase</CardDescription>
                </div>
                <Button
                  onClick={async () => {
                    setGeneratingField('skills');
                    try {
                      const { data } = await portfolioService.generateField('skills', `${headline}\n${about}`);
                      // Parse generated skills (expecting comma-separated list)
                      const newSkills = data.generated.split(',').map(s => s.trim()).filter(Boolean);
                      const uniqueSkills = [...new Set([...skills, ...newSkills])];
                      setSkills(uniqueSkills);
                      showMessage('success', `Added ${newSkills.length} skills (5 credits used)`);
                    } catch (err: unknown) {
                      const error = err as { response?: { status?: number; data?: { error?: string } } };
                      if (error.response?.status === 402) {
                        showMessage('error', 'Insufficient credits — upgrade your plan');
                      } else {
                        showMessage('error', error.response?.data?.error || 'Generation failed');
                      }
                    } finally {
                      setGeneratingField(null);
                    }
                  }}
                  disabled={generatingField === 'skills' || !headline}
                  variant="outline"
                  className="border-[#00F0FF]/30"
                >
                  {generatingField === 'skills' ? (
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  ) : (
                    <Wand2 className="w-4 h-4 mr-2" />
                  )}
                  Generate
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <Input
                  value={newSkill}
                  onChange={(e) => setNewSkill(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && addSkill()}
                  placeholder="e.g. TypeScript, React, Docker..."
                  className="bg-[#06060B] border-[#00F0FF]/30 text-[#E8E8F0]"
                />
                <Button onClick={addSkill} disabled={!newSkill.trim()} className="bg-[#00F0FF] hover:bg-[#00D4B0]">
                  <Plus className="w-4 h-4 mr-2" />Add
                </Button>
              </div>

              {skills.length === 0 ? (
                <div className="text-center py-8">
                  <Code2 className="w-10 h-10 text-[#00F0FF]/30 mx-auto mb-3" />
                  <p className="text-[#6B7280]">No skills added yet</p>
                </div>
              ) : (
                <div className="flex flex-wrap gap-2">
                  {skills.map((skill) => (
                    <button
                      key={skill}
                      onClick={() => removeSkill(skill)}
                      className="group flex items-center gap-1.5 px-4 py-2 min-h-[44px] rounded-full bg-[#00F0FF]/10 border border-[#00F0FF]/30 text-[#00F0FF] hover:bg-[#FF6161]/10 hover:border-[#FF6161]/30 hover:text-[#FF6161] transition-all press-scale"
                    >
                      {skill}
                      <X className="w-3 h-3 opacity-0 group-hover:opacity-100 md:opacity-0 max-md:opacity-60 transition-opacity" />
                    </button>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Projects Tab ────────────────────────────────────── */}
        <TabsContent value="projects" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Projects</CardTitle>
                  <CardDescription className="text-[#6B7280]">Showcase your best work</CardDescription>
                </div>
                <Button
                  onClick={() => { setEditingProject({ ...emptyProject }); setEditingProjectIdx(null); }}
                  className="bg-[#00F0FF] hover:bg-[#00D4B0]"
                >
                  <Plus className="w-4 h-4 mr-2" />Add Project
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Inline project form */}
              {editingProject && (
                <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/30 space-y-3">
                  <div className="grid md:grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm text-[#6B7280] mb-1 block">Name *</label>
                      <Input
                        value={editingProject.name}
                        onChange={(e) => setEditingProject({ ...editingProject, name: e.target.value })}
                        placeholder="Project name"
                        className="bg-[#0C0C18] border-[#00F0FF]/30 text-[#E8E8F0]"
                      />
                    </div>
                    <div>
                      <label className="text-sm text-[#6B7280] mb-1 block">URL</label>
                      <Input
                        value={editingProject.url}
                        onChange={(e) => setEditingProject({ ...editingProject, url: e.target.value })}
                        placeholder="https://..."
                        className="bg-[#0C0C18] border-[#00F0FF]/30 text-[#E8E8F0]"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="text-sm text-[#6B7280] mb-1 block">Description</label>
                    <textarea
                      value={editingProject.description}
                      onChange={(e) => setEditingProject({ ...editingProject, description: e.target.value })}
                      placeholder="What does this project do?"
                      className="w-full p-3 rounded-xl bg-[#0C0C18] border border-[#00F0FF]/30 text-[#E8E8F0] min-h-[80px] resize-none focus:outline-none focus:border-[#00F0FF]"
                    />
                  </div>
                  <div>
                    <label className="text-sm text-[#6B7280] mb-1 block">Tags</label>
                    <div className="flex gap-2 mb-2">
                      <Input
                        value={tagInput}
                        onChange={(e) => setTagInput(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), addTag())}
                        placeholder="Add tag..."
                        className="bg-[#0C0C18] border-[#00F0FF]/30 text-[#E8E8F0]"
                      />
                      <Button onClick={addTag} variant="outline" className="border-[#00F0FF]/30">
                        <Plus className="w-4 h-4" />
                      </Button>
                    </div>
                    {(editingProject.tags || []).length > 0 && (
                      <div className="flex flex-wrap gap-1">
                        {editingProject.tags!.map((tag) => (
                          <Badge
                            key={tag}
                            variant="outline"
                            className="border-[#00F0FF]/30 text-[#6B7280] cursor-pointer hover:border-[#FF6161]/30 hover:text-[#FF6161] min-h-[44px] px-3 py-1.5 press-scale"
                            onClick={() => setEditingProject({ ...editingProject, tags: editingProject.tags!.filter((t) => t !== tag) })}
                          >
                            {tag} <X className="w-3 h-3 ml-1" />
                          </Badge>
                        ))}
                      </div>
                    )}
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" onClick={() => { setEditingProject(null); setEditingProjectIdx(null); setTagInput(''); }} className="border-[#00F0FF]/30">
                      Cancel
                    </Button>
                    <Button onClick={saveProject} disabled={!editingProject.name.trim()} className="bg-[#00F0FF] hover:bg-[#00D4B0]">
                      {editingProjectIdx !== null ? 'Update' : 'Add'}
                    </Button>
                  </div>
                </div>
              )}

              {projects.length === 0 && !editingProject && (
                <div className="text-center py-8">
                  <FolderGit2 className="w-10 h-10 text-[#00F0FF]/30 mx-auto mb-3" />
                  <p className="text-[#6B7280]">No projects yet</p>
                </div>
              )}

              {projects.map((project, idx) => (
                <div key={idx} className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/20 group hover:border-[#00F0FF]/40 transition-all press-scale w-full">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-[#E8E8F0]">{project.name}</h3>
                      {project.description && <p className="text-sm text-[#6B7280] mt-1">{project.description}</p>}
                      {project.url && <p className="text-xs text-[#00F0FF] mt-1 truncate">{project.url}</p>}
                      {(project.tags || []).length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-2">
                          {project.tags!.map((tag) => (
                            <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-[#0C0C18] text-[#6B7280]">{tag}</span>
                          ))}
                        </div>
                      )}
                    </div>
                    <div className="flex gap-1 md:opacity-0 md:group-hover:opacity-100 transition-opacity shrink-0">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => { setEditingProject({ ...project }); setEditingProjectIdx(idx); }}
                        className="text-[#00F0FF] hover:text-[#00F0FF] min-h-[44px] min-w-[44px] press-scale"
                      >
                        Edit
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => deleteProject(idx)}
                        className="text-[#FF6161] hover:text-[#FF6161] min-h-[44px] min-w-[44px] press-scale"
                      >
                        <Trash2 className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Milestones Tab ──────────────────────────────────── */}
        <TabsContent value="milestones" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Milestones</CardTitle>
                  <CardDescription className="text-[#6B7280]">Key achievements and career highlights</CardDescription>
                </div>
                <Button
                  onClick={() => { setEditingMilestone({ ...emptyMilestone }); setEditingMilestoneIdx(null); }}
                  className="bg-[#00F0FF] hover:bg-[#00D4B0]"
                >
                  <Plus className="w-4 h-4 mr-2" />Add Milestone
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              {/* Inline milestone form */}
              {editingMilestone && (
                <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/30 space-y-3">
                  <div className="grid md:grid-cols-2 gap-3">
                    <div>
                      <label className="text-sm text-[#6B7280] mb-1 block">Title *</label>
                      <Input
                        value={editingMilestone.title}
                        onChange={(e) => setEditingMilestone({ ...editingMilestone, title: e.target.value })}
                        placeholder="e.g. Launched SaaS product"
                        className="bg-[#0C0C18] border-[#00F0FF]/30 text-[#E8E8F0]"
                      />
                    </div>
                    <div>
                      <label className="text-sm text-[#6B7280] mb-1 block">Date</label>
                      <Input
                        value={editingMilestone.date}
                        onChange={(e) => setEditingMilestone({ ...editingMilestone, date: e.target.value })}
                        placeholder="2025-01 or Jan 2025"
                        className="bg-[#0C0C18] border-[#00F0FF]/30 text-[#E8E8F0]"
                      />
                    </div>
                  </div>
                  <div>
                    <label className="text-sm text-[#6B7280] mb-1 block">Description</label>
                    <textarea
                      value={editingMilestone.description}
                      onChange={(e) => setEditingMilestone({ ...editingMilestone, description: e.target.value })}
                      placeholder="What happened and why it matters"
                      className="w-full p-3 rounded-xl bg-[#0C0C18] border border-[#00F0FF]/30 text-[#E8E8F0] min-h-[80px] resize-none focus:outline-none focus:border-[#00F0FF]"
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" onClick={() => { setEditingMilestone(null); setEditingMilestoneIdx(null); }} className="border-[#00F0FF]/30">
                      Cancel
                    </Button>
                    <Button onClick={saveMilestone} disabled={!editingMilestone.title.trim()} className="bg-[#00F0FF] hover:bg-[#00D4B0]">
                      {editingMilestoneIdx !== null ? 'Update' : 'Add'}
                    </Button>
                  </div>
                </div>
              )}

              {milestones.length === 0 && !editingMilestone && (
                <div className="text-center py-8">
                  <Award className="w-10 h-10 text-[#00F0FF]/30 mx-auto mb-3" />
                  <p className="text-[#6B7280]">No milestones yet</p>
                </div>
              )}

              {/* Timeline-style list */}
              <div className="space-y-0">
                {milestones.map((milestone, idx) => (
                  <div key={idx} className="flex gap-3 md:gap-4 group">
                    <div className="flex flex-col items-center shrink-0">
                      <div className="w-3 h-3 rounded-full bg-[#00F0FF] mt-1.5" />
                      {idx < milestones.length - 1 && <div className="w-0.5 flex-1 bg-[#00F0FF]/20" />}
                    </div>
                    <div className="flex-1 pb-6 min-w-0">
                      <div className="flex flex-col md:flex-row md:items-start justify-between gap-1">
                        <div className="min-w-0">
                          <div className="text-xs text-[#00F0FF] font-mono mb-1">{milestone.date}</div>
                          <div className="font-medium text-[#E8E8F0]">{milestone.title}</div>
                          {milestone.description && <div className="text-sm text-[#6B7280] mt-1">{milestone.description}</div>}
                        </div>
                        <div className="flex gap-1 md:opacity-0 md:group-hover:opacity-100 transition-opacity shrink-0 mt-2 md:mt-0">
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => { setEditingMilestone({ ...milestone }); setEditingMilestoneIdx(idx); }}
                            className="text-[#00F0FF] hover:text-[#00F0FF] min-h-[44px] min-w-[44px] press-scale"
                          >
                            Edit
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => deleteMilestone(idx)}
                            className="text-[#FF6161] hover:text-[#FF6161] min-h-[44px] min-w-[44px] press-scale"
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Social Links Tab ────────────────────────────────── */}
        <TabsContent value="social" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <CardTitle>Social Links</CardTitle>
              <CardDescription className="text-[#6B7280]">Connect your online presence — all fields are optional</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {([
                { key: 'github' as const, label: 'GitHub', placeholder: 'github.com/username' },
                { key: 'twitter' as const, label: 'Twitter / X', placeholder: 'x.com/username' },
                { key: 'linkedin' as const, label: 'LinkedIn', placeholder: 'linkedin.com/in/username' },
                { key: 'website' as const, label: 'Website', placeholder: 'yoursite.com' },
                { key: 'email' as const, label: 'Email', placeholder: 'you@example.com' },
              ]).map((field) => (
                <div key={field.key}>
                  <label className="text-sm text-[#6B7280] mb-2 block">{field.label}</label>
                  <Input
                    value={social[field.key] || ''}
                    onChange={(e) => setSocial({ ...social, [field.key]: e.target.value })}
                    placeholder={field.placeholder}
                    className="bg-[#06060B] border-[#00F0FF]/30 text-[#E8E8F0]"
                  />
                </div>
              ))}
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── AI Edit Tab ─────────────────────────────────────── */}
        <TabsContent value="ai" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-[#00F0FF]" />
                AI Portfolio Editor
              </CardTitle>
              <CardDescription className="text-[#6B7280]">
                Describe changes in plain English and let AI update your portfolio
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <textarea
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="e.g. Make my bio more professional, add a React project, rewrite my headline to focus on AI engineering..."
                className="w-full p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/30 text-[#E8E8F0] min-h-[140px] resize-none focus:outline-none focus:border-[#00F0FF]"
              />
              <Button
                onClick={handleAiEdit}
                disabled={aiLoading || !aiPrompt.trim()}
                className="bg-[#00F0FF] hover:bg-[#00D4B0] w-full"
              >
                {aiLoading ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" />Applying...</>
                ) : (
                  <><Sparkles className="w-4 h-4 mr-2" />Apply AI Edit</>
                )}
              </Button>
              <p className="text-xs text-[#6B7280] text-center">
                Changes are applied locally — review them in the other tabs, then click Save Changes to persist.
              </p>
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Suggestions Tab ─────────────────────────────────── */}
        <TabsContent value="suggestions" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lightbulb className="w-5 h-5 text-[#00F0FF]" />
                Memory-Driven Suggestions
              </CardTitle>
              <CardDescription className="text-[#6B7280]">
                AI found these portfolio-worthy items from your conversations
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              {loadingSuggestions ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="w-6 h-6 text-[#00F0FF] animate-spin" />
                </div>
              ) : suggestions.length === 0 ? (
                <div className="text-center py-12">
                  <Lightbulb className="w-12 h-12 text-[#00F0FF]/30 mx-auto mb-4" />
                  <p className="text-[#6B7280] mb-2">No suggestions yet</p>
                  <p className="text-sm text-[#6B7280]/70">
                    Chat with your agent about projects and accomplishments — suggestions will appear here.
                  </p>
                </div>
              ) : (
                <div className="space-y-3">
                  {suggestions.map((suggestion) => (
                    <div
                      key={suggestion.id}
                      className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/20 hover:border-[#00F0FF]/40 transition-all"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-2">
                            <Badge variant="outline" className="border-[#00F0FF]/30 text-[#00F0FF]">
                              {suggestion.field}
                            </Badge>
                            <span className="text-xs text-[#6B7280]">
                              {Math.round(suggestion.confidence * 100)}% confidence
                            </span>
                          </div>
                          <p className="text-sm text-[#E8E8F0] mb-1">{suggestion.reason}</p>
                          <p className="text-sm text-[#6B7280] line-clamp-2">{suggestion.suggestedValue}</p>
                        </div>
                        <Button
                          onClick={() => handleApplySuggestion(suggestion.id)}
                          disabled={applyingSuggestion === suggestion.id}
                          size="sm"
                          className="bg-[#00FF88]/10 border border-[#00FF88]/30 text-[#00FF88] hover:bg-[#00FF88]/20 shrink-0"
                        >
                          {applyingSuggestion === suggestion.id ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <><CheckCircle2 className="w-4 h-4 mr-1" />Apply</>
                          )}
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
              <p className="text-xs text-[#6B7280] text-center pt-4">
                Suggestions are based on memories from your agent conversations. Review before applying.
              </p>
            </CardContent>
          </Card>
        </TabsContent>

        {/* ── Analytics Tab ──────────────────────────────────── */}
        <TabsContent value="analytics" className="space-y-6">
          <Card className="border-[#00F0FF]/20">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="w-5 h-5 text-[#00F0FF]" />
                Portfolio Analytics
              </CardTitle>
              <CardDescription className="text-[#6B7280]">
                Track views, engagement, and visitor insights
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* Stats Grid */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/10">
                  <div className="flex items-center gap-2 mb-2">
                    <Eye className="w-4 h-4 text-[#00F0FF]" />
                    <span className="text-xs text-[#6B7280]">Total Views</span>
                  </div>
                  <div className="text-2xl font-bold text-[#E8E8F0]">1,234</div>
                  <div className="text-xs text-[#00FF88]">↑ 12% this week</div>
                </div>
                <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/10">
                  <div className="flex items-center gap-2 mb-2">
                    <MousePointer className="w-4 h-4 text-[#00FF88]" />
                    <span className="text-xs text-[#6B7280]">Click Rate</span>
                  </div>
                  <div className="text-2xl font-bold text-[#E8E8F0]">8.5%</div>
                  <div className="text-xs text-[#6B7280]">Industry avg: 5.2%</div>
                </div>
                <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/10">
                  <div className="flex items-center gap-2 mb-2">
                    <Globe className="w-4 h-4 text-[#FF2D78]" />
                    <span className="text-xs text-[#6B7280]">Countries</span>
                  </div>
                  <div className="text-2xl font-bold text-[#E8E8F0]">12</div>
                  <div className="text-xs text-[#6B7280]">Top: US, India, UK</div>
                </div>
                <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/10">
                  <div className="flex items-center gap-2 mb-2">
                    <TrendingUp className="w-4 h-4 text-[#FFB800]" />
                    <span className="text-xs text-[#6B7280]">Connections</span>
                  </div>
                  <div className="text-2xl font-bold text-[#E8E8F0]">47</div>
                  <div className="text-xs text-[#00FF88]">↑ 5 new this week</div>
                </div>
              </div>

              {/* Coming Soon Notice */}
              <div className="p-6 rounded-xl bg-[#00F0FF]/5 border border-[#00F0FF]/20 text-center">
                <BarChart3 className="w-12 h-12 text-[#00F0FF]/50 mx-auto mb-3" />
                <h4 className="text-lg font-medium text-[#E8E8F0] mb-2">Detailed Analytics Coming Soon</h4>
                <p className="text-sm text-[#6B7280] max-w-md mx-auto">
                  We're building comprehensive analytics including referrer tracking, 
                  project engagement heatmaps, and visitor demographics.
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Generated Preview Modal */}
      {generatedPreview && generateTarget && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="glass-card-v2 border border-[#00F0FF]/30 rounded-2xl max-w-lg w-full p-6 space-y-4 animate-in fade-in zoom-in duration-200">
            <div className="flex items-center gap-2">
              <Wand2 className="w-5 h-5 text-[#00F0FF]" />
              <h3 className="text-lg font-semibold text-[#E8E8F0]">Generated {generateTarget.field}</h3>
            </div>
            <div className="p-4 rounded-xl bg-[#06060B] border border-[#00F0FF]/20">
              <p className="text-[#E8E8F0] whitespace-pre-wrap">{generatedPreview}</p>
            </div>
            <div className="flex gap-3">
              <Button
                onClick={discardGenerated}
                variant="outline"
                className="flex-1 border-[#00F0FF]/30"
              >
                Discard
              </Button>
              <Button
                onClick={applyGenerated}
                className="flex-1 bg-[#00F0FF] hover:bg-[#00D4B0]"
              >
                <CheckCircle2 className="w-4 h-4 mr-2" />
                Apply
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
