#!/bin/bash
# pr-phase.sh: Create a GitHub PR from the current branch → main
# Called via SSH from OpenClaw's pr-create bin
# Usage: bash scripts/pr-phase.sh --phase <name> --type <type> --tests <count>
# Outputs: PR URL on stdout

set -euo pipefail

PHASE_NAME=""
AGENT_TYPE="builder"
TEST_COUNT=""
BRANCH_ARG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --phase)  PHASE_NAME="$2"; shift 2 ;;
    --type)   AGENT_TYPE="$2"; shift 2 ;;
    --tests)  TEST_COUNT="$2"; shift 2 ;;
    --branch) BRANCH_ARG="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Use GITHUB_DEV_TOKEN from .env if gh auth isn't working
if [[ -f "$(dirname "$0")/../.env" ]]; then
  source <(grep -E "^GITHUB_DEV_TOKEN=" "$(dirname "$0")/../.env") 2>/dev/null || true
fi
export GH_TOKEN="${GITHUB_DEV_TOKEN:-${GH_TOKEN:-}}"

# Use explicit branch if provided, otherwise fall back to current branch
if [[ -n "$BRANCH_ARG" ]]; then
  BRANCH="$BRANCH_ARG"
  # Checkout the branch so git log shows the right commits
  git fetch origin "$BRANCH" --quiet 2>/dev/null || true
  git checkout "$BRANCH" --quiet 2>/dev/null || true
else
  BRANCH=$(git branch --show-current 2>/dev/null || echo "")
fi

if [[ -z "$BRANCH" || "$BRANCH" == "main" ]]; then
  echo "[pr-phase] ERROR: Not on a feature branch (got: ${BRANCH:-none})" >&2
  exit 1
fi

# Build PR title from phase name
TITLE=$(echo "$PHASE_NAME" | sed 's/-/ /g' | sed 's/phase /Phase /g')
TYPE_LABEL=$(echo "$AGENT_TYPE" | tr '[:upper:]' '[:lower:]')

# Test count display
TESTS_LINE=""
if [[ -n "$TEST_COUNT" ]]; then
  TESTS_LINE="- **Tests passing:** $TEST_COUNT"
fi

# Get last 3 commits for body
COMMITS=$(git log --oneline -3 2>/dev/null | sed 's/^/  - /' || echo "  - (no commits)")

PR_BODY="## 🤖 Auto-generated by OpenClaw Factory

**Phase:** \`$PHASE_NAME\`
**Agent type:** $AGENT_TYPE
**Branch:** \`$BRANCH\`
$TESTS_LINE

### Recent commits:
$COMMITS

---
*This PR was created automatically by the OpenClaw factory pipeline.*
*Review changes, then merge when ready.*"

# Create the PR
PR_URL=$(gh pr create \
  --base main \
  --title "feat($TYPE_LABEL): $TITLE" \
  --body "$PR_BODY" \
  --label "auto/factory" 2>/dev/null || echo "")

if [[ -z "$PR_URL" ]]; then
  # Try without label (label might not exist yet)
  PR_URL=$(gh pr create \
    --base main \
    --title "feat($TYPE_LABEL): $TITLE" \
    --body "$PR_BODY" 2>/dev/null || echo "")
fi

if [[ -z "$PR_URL" ]]; then
  echo "[pr-phase] ERROR: gh pr create failed. Check GH_TOKEN / gh auth status" >&2
  exit 1
fi

echo "$PR_URL"
