apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.50.0
      cacheLevel: 'High'
      incrementalQuerying: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      manageAlerts: true
      derivedFields:
        - name: 'TraceID'
          matcherRegex: 'trace_id=(\\w+)'
          url: '$${__value.raw}'
        - name: 'SpanID'
          matcherRegex: 'span_id=(\\w+)'
          url: '$${__value.raw}'
